export type BankQuestion = {
  id: string;
  section: "tcs-aptitude" | "tcs-coding" | "oops" | "dbms" | "os" | "cn" | "hr";
  title: string;
  prompt: string;
  kind: "mcq" | "short" | "code-prompt";
  options?: string[];
  answer?: string;
  explanation?: string;
};

export const interviewBank: BankQuestion[] = [
  // TCS NQT aptitude
  {
    id: "tcs-a1",
    section: "tcs-aptitude",
    title: "Percentages",
    prompt: "A number is increased by 20% and then decreased by 20%. Net change?",
    kind: "mcq",
    options: ["No change", "4% decrease", "4% increase", "20% decrease"],
    answer: "4% decrease",
    explanation: "1.2 * 0.8 = 0.96 → 4% loss.",
  },
  {
    id: "tcs-a2",
    section: "tcs-aptitude",
    title: "Time & Work",
    prompt: "A finishes in 10 days, B in 15. Together how many days?",
    kind: "mcq",
    options: ["5", "6", "8", "12"],
    answer: "6",
    explanation: "1/10+1/15=1/6 → 6 days.",
  },
  {
    id: "tcs-a3",
    section: "tcs-aptitude",
    title: "Number series",
    prompt: "2, 6, 12, 20, 30, ?",
    kind: "mcq",
    options: ["36", "40", "42", "44"],
    answer: "42",
    explanation: "n(n+1): 1*2,2*3,3*4,4*5,5*6,6*7=42.",
  },
  {
    id: "tcs-a4",
    section: "tcs-aptitude",
    title: "Profit & Loss",
    prompt: "CP=500, SP=575. Profit %?",
    kind: "mcq",
    options: ["12%", "15%", "15.5%", "20%"],
    answer: "15%",
    explanation: "75/500*100=15%.",
  },
  {
    id: "tcs-a5",
    section: "tcs-aptitude",
    title: "Ages",
    prompt: "Father is 3 times son. In 12 years he will be twice. Son's present age?",
    kind: "mcq",
    options: ["12", "14", "16", "18"],
    answer: "12",
    explanation: "3x+12=2(x+12) → x=12.",
  },
  // TCS coding prompts
  {
    id: "tcs-c1",
    section: "tcs-coding",
    title: "Reverse digits",
    prompt: "Write C++ logic to reverse digits of an integer without using strings. Discuss overflow.",
    kind: "short",
  },
  {
    id: "tcs-c2",
    section: "tcs-coding",
    title: "Frequency of characters",
    prompt: "Given a lowercase string, explain O(n) approach to print frequency of each character.",
    kind: "short",
  },
  {
    id: "tcs-c3",
    section: "tcs-coding",
    title: "Prime check",
    prompt: "Optimize isPrime(n) better than checking all numbers till n-1. What is complexity?",
    kind: "short",
  },
  // OOPs
  {
    id: "oops-1",
    section: "oops",
    title: "Encapsulation vs Abstraction",
    prompt: "Difference between encapsulation and abstraction with a C++ example idea.",
    kind: "short",
  },
  {
    id: "oops-2",
    section: "oops",
    title: "Virtual functions",
    prompt: "Why do we need virtual functions? What is a vtable at a high level?",
    kind: "short",
  },
  {
    id: "oops-3",
    section: "oops",
    title: "Copy constructor",
    prompt: "When should you write your own copy constructor in C++?",
    kind: "short",
  },
  // DBMS
  {
    id: "dbms-1",
    section: "dbms",
    title: "Normalization",
    prompt: "Explain 1NF, 2NF, 3NF in one sentence each with why we care in interviews.",
    kind: "short",
  },
  {
    id: "dbms-2",
    section: "dbms",
    title: "Indexes",
    prompt: "When does an index help SELECT but hurt INSERT/UPDATE? Tradeoff?",
    kind: "short",
  },
  {
    id: "dbms-3",
    section: "dbms",
    title: "ACID",
    prompt: "Expand ACID and give a real-world analogy for Atomicity.",
    kind: "short",
  },
  // OS
  {
    id: "os-1",
    section: "os",
    title: "Process vs Thread",
    prompt: "Process vs Thread — memory, creation cost, when to use which.",
    kind: "short",
  },
  {
    id: "os-2",
    section: "os",
    title: "Deadlock",
    prompt: "Four Coffman conditions for deadlock. Name one prevention strategy.",
    kind: "short",
  },
  {
    id: "os-3",
    section: "os",
    title: "Scheduling",
    prompt: "Compare FCFS, SJF, Round Robin in one line each.",
    kind: "short",
  },
  // CN
  {
    id: "cn-1",
    section: "cn",
    title: "TCP vs UDP",
    prompt: "TCP vs UDP — reliability, ordering, use-cases.",
    kind: "short",
  },
  {
    id: "cn-2",
    section: "cn",
    title: "HTTP vs HTTPS",
    prompt: "What does HTTPS add on top of HTTP? Where do certificates fit?",
    kind: "short",
  },
  {
    id: "cn-3",
    section: "cn",
    title: "OSI quick",
    prompt: "Name OSI layers and one protocol/example at Transport and Application.",
    kind: "short",
  },
  // HR
  {
    id: "hr-1",
    section: "hr",
    title: "Tell me about yourself",
    prompt: "Draft a 60–90 second intro for a 2027 fresher aiming software roles (C++/DSA focus).",
    kind: "short",
  },
  {
    id: "hr-2",
    section: "hr",
    title: "Failure story (STAR)",
    prompt: "Describe a technical failure using STAR (Situation, Task, Action, Result).",
    kind: "short",
  },
  {
    id: "hr-3",
    section: "hr",
    title: "Why TCS / service company?",
    prompt: "Answer 'Why should we hire you?' for a product-or-service company interview.",
    kind: "short",
  },
  {
    id: "hr-4",
    section: "hr",
    title: "Conflict",
    prompt: "Team conflict over approach — how do you handle it?",
    kind: "short",
  },
  // More TCS aptitude variety
  {
    id: "tcs-a6",
    section: "tcs-aptitude",
    title: "Simple Interest",
    prompt: "P=1000, R=10%, T=2 years. SI?",
    kind: "mcq",
    options: ["100", "200", "220", "210"],
    answer: "200",
    explanation: "SI = PRT/100 = 1000*10*2/100 = 200.",
  },
  {
    id: "tcs-a7",
    section: "tcs-aptitude",
    title: "Ratio",
    prompt: "A:B = 2:3, B:C = 4:5. A:C?",
    kind: "mcq",
    options: ["8:15", "2:5", "8:9", "4:5"],
    answer: "8:15",
    explanation: "A:B=2:3=8:12, B:C=4:5=12:15 → A:C=8:15.",
  },
  {
    id: "tcs-a8",
    section: "tcs-aptitude",
    title: "Average",
    prompt: "Avg of 5 numbers is 20. If one number 30 is replaced by 40, new avg?",
    kind: "mcq",
    options: ["21", "22", "23", "24"],
    answer: "22",
    explanation: "Sum was 100; becomes 110; avg=22.",
  },
  {
    id: "tcs-a9",
    section: "tcs-aptitude",
    title: "Pipes",
    prompt: "Pipe A fills in 6h, B empties in 8h. Together fill time from empty?",
    kind: "mcq",
    options: ["24h", "14h", "10h", "48h"],
    answer: "24h",
    explanation: "1/6 - 1/8 = 1/24 → 24 hours.",
  },
  {
    id: "tcs-a10",
    section: "tcs-aptitude",
    title: "Probability",
    prompt: "A fair die. P(prime number)?",
    kind: "mcq",
    options: ["1/2", "1/3", "1/6", "2/3"],
    answer: "1/2",
    explanation: "Primes 2,3,5 → 3/6=1/2.",
  },
  {
    id: "tcs-a11",
    section: "tcs-aptitude",
    title: "Blood relations",
    prompt: "A is B's brother. C is A's mother. D is C's father. How is D related to B?",
    kind: "mcq",
    options: ["Father", "Grandfather", "Uncle", "Son"],
    answer: "Grandfather",
    explanation: "D is father of C, C is mother of A/B → maternal grandfather.",
  },
  {
    id: "tcs-a12",
    section: "tcs-aptitude",
    title: "Coding-decoding",
    prompt: "If CAT = 24, DOG = 26, what is BAT?",
    kind: "mcq",
    options: ["23", "20", "22", "21"],
    answer: "23",
    explanation: "Sum of positions: B+A+T=2+1+20=23 (pattern variants exist; here position sum).",
  },
  {
    id: "tcs-c4",
    section: "tcs-coding",
    title: "Palindrome number",
    prompt: "Check if an integer is palindrome without converting to string. How?",
    kind: "short",
  },
  {
    id: "tcs-c5",
    section: "tcs-coding",
    title: "Second largest",
    prompt: "Find second largest in array in one pass. Edge cases?",
    kind: "short",
  },
  {
    id: "tcs-c6",
    section: "tcs-coding",
    title: "Anagram check",
    prompt: "Are two strings anagrams? Give O(n) approach in C++.",
    kind: "short",
  },
  {
    id: "oops-4",
    section: "oops",
    title: "Inheritance types",
    prompt: "Single vs multiple inheritance in C++. Diamond problem — how does virtual inheritance help?",
    kind: "short",
  },
  {
    id: "oops-5",
    section: "oops",
    title: "Polymorphism",
    prompt: "Compile-time vs runtime polymorphism examples in C++.",
    kind: "short",
  },
  {
    id: "dbms-4",
    section: "dbms",
    title: "Joins",
    prompt: "INNER vs LEFT JOIN — when do you get NULLs?",
    kind: "short",
  },
  {
    id: "dbms-5",
    section: "dbms",
    title: "Transactions isolation",
    prompt: "Name dirty read / non-repeatable read / phantom. Which isolation stops dirty reads?",
    kind: "short",
  },
  {
    id: "os-4",
    section: "os",
    title: "Virtual memory",
    prompt: "What is paging? What is a page fault at a high level?",
    kind: "short",
  },
  {
    id: "os-5",
    section: "os",
    title: "Mutex vs semaphore",
    prompt: "Mutex vs binary semaphore — key differences for interviews.",
    kind: "short",
  },
  {
    id: "cn-4",
    section: "cn",
    title: "DNS",
    prompt: "What does DNS do? Walk a browser request from URL to IP at a high level.",
    kind: "short",
  },
  {
    id: "cn-5",
    section: "cn",
    title: "3-way handshake",
    prompt: "Explain TCP 3-way handshake in 3 bullets.",
    kind: "short",
  },
  {
    id: "hr-5",
    section: "hr",
    title: "Strength / weakness",
    prompt: "One real strength and one weakness with how you're improving (no fake clichés).",
    kind: "short",
  },
  {
    id: "hr-6",
    section: "hr",
    title: "5 years",
    prompt: "Where do you see yourself in 5 years? Keep it grounded for 2027 fresher path.",
    kind: "short",
  },
];

export function bankBySection(section: BankQuestion["section"]) {
  return interviewBank.filter((q) => q.section === section);
}
