import { EXTRA_SHOWS, PROBLEM_SHOW_EXTRA } from "./teacher-shows-bank";

export type ShowKind = "array-scan" | "two-pointers" | "sliding-window" | "hash-map" | "kadane";

export type ShowGesture = "point" | "think" | "write" | "celebrate" | "explain";

export type ShowStep = {
  /** Teacher line — Hinglish */
  say: string;
  sayEn?: string;
  sayHi?: string;
  /** Array values for this frame */
  cells?: number[] | string[];
  /** Highlighted indices */
  hi?: number[];
  /** Named pointers */
  pointers?: Record<string, number>;
  /** Hash map snapshot */
  map?: Record<string, string | number>;
  /** Running stats */
  stats?: Record<string, string | number>;
  /** Window [L,R] inclusive */
  window?: [number, number];
  /** One line of the optimal code this frame is teaching */
  codeLine?: string;
  /** Teacher body language for this beat */
  gesture?: ShowGesture;
  /** Short chalkboard heading */
  board?: string;
  /** Course chapter label */
  chapter?: string;
};

export type TeacherShowScript = {
  id: string;
  title: string;
  subtitle: string;
  kind: ShowKind;
  durationHint: string;
  steps: ShowStep[];
  /** Linked practice problem ids */
  practiceIds: string[];
};

export const teacherShows: Record<string, TeacherShowScript> = {
  "two-sum-show": {
    id: "two-sum-show",
    title: "Two Sum — Hash Map Walk",
    subtitle: "YouTube-style dry run: watch the map fill, then the hit.",
    kind: "hash-map",
    durationHint: "~2 min",
    practiceIds: ["two-sum", "two-sum-hash"],
    steps: [
      {
        chapter: "Hook",
        board: "Two Sum",
        gesture: "explain",
        say: "Suno. Problem bilkul simple hai. Array mein numbers hain. Target diya hai. Do aise numbers chahiye jinka sum target ke barabar ho.",
        sayEn: "Listen. The problem is simple. You get an array of numbers and a target. Find two numbers whose sum equals the target.",
        sayHi: "सुनो। समस्या बिलकुल आसान है। ऐरे में नंबर हैं। टारगेट दिया है। दो ऐसे नंबर चाहिए जिनका योग टारगेट के बराबर हो।",
        cells: [2, 7, 11, 15],
        stats: { target: 9, ask: "which two add to 9?" },
      },
      {
        chapter: "Contract",
        board: "Return indexes, not values",
        gesture: "point",
        say: "Dhyan se. Humein numbers nahi return karne. Unke index return karne hain. 2 aur 7 ka jawab 0 aur 1 hai.",
        sayEn: "Careful. We do not return the numbers. We return their indexes. For 2 and 7, the answer is 0 and 1.",
        sayHi: "ध्यान से। हमें नंबर नहीं रिटर्न करने। उनके इंडेक्स रिटर्न करने हैं। 2 और 7 का जवाब 0 और 1 है।",
        cells: [2, 7, 11, 15],
        hi: [0, 1],
        stats: { return: "[0, 1]" },
      },
      {
        chapter: "Wrong path",
        board: "Brute force = O(n²)",
        gesture: "think",
        say: "Pehla tareeka. Har pair try karo. Chalega. Par time bahut slow ho jaata hai. Interview mein better chahiye.",
        sayEn: "First way. Try every pair. It works. But it is too slow. Interviews want better.",
        sayHi: "पहला तरीका। हर पेयर ट्राई करो। चलेगा। पर बहुत धीमा है। इंटरव्यू में बेहतर चाहिए।",
        cells: [2, 7, 11, 15],
        stats: { brute: "every pair", time: "too slow" },
      },
      {
        chapter: "The idea",
        board: "Diary = hash map",
        gesture: "write",
        say: "Ab socho. Better idea. Ek diary rakho. Har value ke saath uska index yaad rakhna. Yeh diary hash map hai.",
        sayEn: "Now think. Better idea. Keep a diary. Remember each value with its index. That diary is the hash map.",
        sayHi: "अब सोचो। बेहतर आइडिया। एक डायरी रखो। हर वैल्यू के साथ उसका इंडेक्स याद रखना। यही हैश मैप है।",
        cells: [2, 7, 11, 15],
        map: {},
        stats: { diary: "empty hash map" },
        codeLine: "unordered_map<int,int> seen;",
      },
      {
        chapter: "The trick",
        board: "need = target − current",
        gesture: "explain",
        say: "Trick yeh hai. Current number pe aao. Pocho. Target minus current, kya pehle se diary mein hai?",
        sayEn: "Here is the trick. Stand on the current number. Ask. Is target minus current already in the diary?",
        sayHi: "ट्रिक यह है। करंट नंबर पर आओ। पूछो। टारगेट माइनस करंट, क्या पहले से डायरी में है?",
        cells: [2, 7, 11, 15],
        map: {},
        stats: { trick: "need = target - current" },
        codeLine: "int need = target - nums[i];",
      },
      {
        chapter: "Dry run",
        board: "i = 0 · need 7?",
        gesture: "point",
        say: "Dry run. Index zero. Value 2. Need 9 minus 2, matlab 7. Diary khali hai. 7 nahi mila.",
        sayEn: "Dry run. Index 0. Value 2. Need is 9 minus 2, that is 7. Diary is empty. No 7 yet.",
        sayHi: "ड्राई रन। इंडेक्स 0। वैल्यू 2। नीड 9 माइनस 2, मतलब 7। डायरी खाली है। 7 नहीं मिला।",
        cells: [2, 7, 11, 15],
        hi: [0],
        pointers: { i: 0 },
        map: {},
        stats: { need: 7, found: "no" },
      },
      {
        chapter: "Dry run",
        board: "Store 2 → 0",
        gesture: "write",
        say: "Isliye 2 ko diary mein likh do. Value 2, index zero. Ab aage badho.",
        sayEn: "So write 2 into the diary. Value 2, index 0. Now move ahead.",
        sayHi: "इसलिए 2 को डायरी में लिख दो। वैल्यू 2, इंडेक्स 0। अब आगे बढ़ो।",
        cells: [2, 7, 11, 15],
        hi: [0],
        pointers: { i: 0 },
        map: { "2": 0 },
        stats: { action: "store 2 → 0" },
        codeLine: "seen[2] = 0;",
      },
      {
        chapter: "Dry run",
        board: "i = 1 · HIT!",
        gesture: "celebrate",
        say: "Index one. Value 7. Need 9 minus 7, matlab 2. Diary kholo. 2 pehle se index zero pe hai. Hit!",
        sayEn: "Index 1. Value 7. Need is 9 minus 7, that is 2. Open the diary. 2 is already at index 0. Hit!",
        sayHi: "इंडेक्स 1। वैल्यू 7। नीड 9 माइनस 7, मतलब 2। डायरी खोलो। 2 पहले से इंडेक्स 0 पर है। हिट!",
        cells: [2, 7, 11, 15],
        hi: [0, 1],
        pointers: { i: 1 },
        map: { "2": 0 },
        stats: { need: 2, found: "YES @ 0" },
        codeLine: "return {0, 1};",
      },
      {
        chapter: "Wrap",
        board: "One pass. Done.",
        gesture: "celebrate",
        say: "Bas. Answer zero aur one. Ek baar array ghumna. Diary se turant partner mil gaya. Ab tum khud code likho.",
        sayEn: "Done. Answer is 0 and 1. One walk through the array. The diary finds the partner instantly. Now you type the code.",
        sayHi: "बस। जवाब 0 और 1। एक बार ऐरे घूमना। डायरी से तुरंत पार्टनर मिल गया। अब खुद कोड लिखो।",
        cells: [2, 7, 11, 15],
        hi: [0, 1],
        map: { "2": 0 },
        stats: { answer: "[0, 1]", time: "one pass" },
      },
    ],
  },
  "two-pointers-water": {
    id: "two-pointers-water",
    title: "Container With Most Water",
    subtitle: "L and R dance — always move the shorter wall.",
    kind: "two-pointers",
    durationHint: "~2 min",
    practiceIds: ["container-most-water"],
    steps: [
      {
        chapter: "Hook",
        board: "Container With Most Water",
        gesture: "explain",
        say: "Suno. Height array diya hai. Do walls choose karo. Pani kitna bhar sakte ho? Area = min height × width.",
        sayEn: "Listen. You get a height array. Pick two walls. How much water fits? Area = min height × width.",
        sayHi: "सुनो। हाइट ऐरे दिया है। दो दीवारें चुनो। पानी कितना भर सकते हो? एरिया = मिन हाइट × चौड़ाई।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        stats: { ask: "max area?" },
      },
      {
        chapter: "Contract",
        board: "Two lines, not adjacent",
        gesture: "point",
        say: "Do indexes i aur j. Width j minus i. Height dono mein chhoti wall. Max area return.",
        sayEn: "Two indexes i and j. Width is j minus i. Height is the shorter wall. Return max area.",
        sayHi: "दो इंडेक्स i और j। चौड़ाई j माइनस i। हाइट छोटी दीवार। मैक्स एरिया रिटर्न।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        stats: { formula: "min(h[i],h[j])*(j-i)" },
      },
      {
        chapter: "Wrong path",
        board: "Every pair O(n²)",
        gesture: "think",
        say: "Har pair try karo. Chalega. Par n bada ho to slow. Two pointers se O(n) possible.",
        sayEn: "Try every pair. It works. But slow for large n. Two pointers give O(n).",
        sayHi: "हर पेयर ट्राई करो। चलेगा। पर n बड़ा हो तो धीमा। टू पॉइंटर्स से O(n) संभव।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        stats: { brute: "all pairs", time: "O(n²)" },
      },
      {
        chapter: "The idea",
        board: "L and R at ends",
        gesture: "write",
        say: "Idea. L start pe, R end pe. Area calculate karo. Best update karo.",
        sayEn: "Idea. L at start, R at end. Compute area. Update best.",
        sayHi: "आइडिया। L शुरू पर, R अंत पर। एरिया निकालो। बेस्ट अपडेट।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        pointers: { L: 0, R: 8 },
        window: [0, 8],
        stats: { start: "wide window" },
        codeLine: "int L = 0, R = n - 1, best = 0;",
      },
      {
        chapter: "The trick",
        board: "Move shorter wall",
        gesture: "explain",
        say: "Trick. Chhoti height wali side move karo. Kyunki badi side rakh ke sirf width ghat-ti hai — area nahi badhega.",
        sayEn: "Trick. Move the shorter side. Keeping the taller side only shrinks width — area cannot improve.",
        sayHi: "ट्रिक। छोटी हाइट वाली साइड हिलाओ। बड़ी रखoge तो सिर्फ चौड़ाई घटे — एरिया नहीं बढ़ेगा।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        pointers: { L: 0, R: 8 },
        stats: { rule: "if h[L] < h[R] L++ else R--" },
        codeLine: "if (height[L] < height[R]) ++L; else --R;",
      },
      {
        chapter: "Dry run",
        board: "L=0, R=8 · area 8",
        gesture: "point",
        say: "Pehla frame. min(1,7)×8 = 8. Best = 8. Left chhoti — L++.",
        sayEn: "First frame. min(1,7)×8 = 8. Best = 8. Left is shorter — L++.",
        sayHi: "पहला फ्रेम। min(1,7)×8 = 8। बेस्ट = 8। लेफ्ट छोटी — L++।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        pointers: { L: 0, R: 8 },
        window: [0, 8],
        stats: { area: 8, best: 8 },
      },
      {
        chapter: "Dry run",
        board: "L=1, R=8 · best 49!",
        gesture: "write",
        say: "L index one pe height 8. min(8,7)×7 = 49. Best update! Yeh abhi tak ka winner.",
        sayEn: "L at index 1, height 8. min(8,7)×7 = 49. Best update! Current winner.",
        sayHi: "L इंडेक्स 1 पर हाइट 8। min(8,7)×7 = 49। बेस्ट अपडेट! अभी का विजेता।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        hi: [1, 8],
        pointers: { L: 1, R: 8 },
        window: [1, 8],
        stats: { area: 49, best: 49 },
      },
      {
        chapter: "Dry run",
        board: "Keep moving shorter",
        gesture: "point",
        say: "Right chhoti (3 < 8) → R--. Area 18. Best 49 rehta. Jab tak L < R, chalte raho.",
        sayEn: "Right is shorter (3 < 8) → R--. Area 18. Best stays 49. Continue while L < R.",
        sayHi: "राइट छोटी (3 < 8) → R--। एरिया 18। बेस्ट 49। जब तक L < R, चलते रहो।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        hi: [1, 7],
        pointers: { L: 1, R: 7 },
        window: [1, 7],
        stats: { area: 18, best: 49 },
      },
      {
        chapter: "Wrap",
        board: "Answer 49",
        gesture: "celebrate",
        say: "Bas. Answer 49. O(n) time, O(1) space. Shorter wall move — yahi pattern. Ab tum likho.",
        sayEn: "Done. Answer is 49. O(n) time, O(1) space. Move the shorter wall — that is the pattern. Now you write it.",
        sayHi: "बस। जवाब 49। O(n) टाइम, O(1) स्पेस। छोटी दीवार हिलाओ — यही पैटर्न। अब तुम लिखो।",
        cells: [1, 8, 6, 2, 5, 4, 8, 3, 7],
        hi: [1, 8],
        pointers: { L: 1, R: 8 },
        stats: { answer: 49, time: "O(n)" },
        codeLine: "return best;",
      },
    ],
  },
  "sliding-window-unique": {
    id: "sliding-window-unique",
    title: "Longest Substring Without Repeat",
    subtitle: "Window grow with R, shrink with L when duplicate aata hai.",
    kind: "sliding-window",
    durationHint: "~2 min",
    practiceIds: ["longest-substr-no-repeat"],
    steps: [
      {
        chapter: "Hook",
        board: "Longest Unique Substring",
        gesture: "explain",
        say: "Suno. String di hai. Sabse lambi substring chahiye jisme koi character do baar na aaye.",
        sayEn: "Listen. You get a string. Find the longest substring with no repeated character.",
        sayHi: "सुनो। स्ट्रिंग दी है। सबसे लंबी सबस्ट्रिंग चाहिए जिसमें कोई कैरेक्टर दो बार न आए।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        stats: { ask: "max length?" },
      },
      {
        chapter: "Contract",
        board: "Return length int",
        gesture: "point",
        say: "Substring continuous honi chahiye. Example abcabcbb ka jawab 3 — \"abc\".",
        sayEn: "Substring must be contiguous. For abcabcbb the answer is 3 — \"abc\".",
        sayHi: "सबस्ट्रिंग लगातार होनी चाहिए। abcabcbb का जवाब 3 — \"abc\"।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        stats: { return: "length int" },
      },
      {
        chapter: "Wrong path",
        board: "Check every substring",
        gesture: "think",
        say: "Har substring check karo with set. O(n²) ya worse. Sliding window O(n) karta hai.",
        sayEn: "Check every substring with a set. O(n²) or worse. Sliding window does O(n).",
        sayHi: "हर सबस्ट्रिंग सेट से चेक? O(n²) या worse। स्लाइडिंग विंडो O(n) करता है।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        stats: { avoid: "O(n²) substrings" },
      },
      {
        chapter: "The idea",
        board: "L and R window",
        gesture: "write",
        say: "Idea. R se window badhao. Set ya map mein chars rakho. Duplicate aaye to L se shrink.",
        sayEn: "Idea. Expand with R. Track chars in a set or map. On duplicate, shrink from L.",
        sayHi: "आइडिया। R से विंडो बढ़ाओ। सेट/मैप में कैरेक्टर्स। डुप्लिकेट आए तो L से श्रिंक।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        pointers: { L: 0, R: 0 },
        window: [0, 0],
        map: {},
        codeLine: "int L = 0, best = 0;",
      },
      {
        chapter: "The trick",
        board: "Shrink until clean",
        gesture: "explain",
        say: "Trick. Jab s[R] pehle se window mein ho, L++ jab tak woh char bahar na ho. Phir R add karo.",
        sayEn: "Trick. When s[R] is already in the window, L++ until that char leaves. Then add R.",
        sayHi: "ट्रिक। जब s[R] पहले से विंडो में, L++ जब तक वो बाहर न हो। फिर R ऐड।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        stats: { rule: "while dup: L++" },
        codeLine: "while (seen.count(s[R])) { seen.erase(s[L++]); }",
      },
      {
        chapter: "Dry run",
        board: "R grows · abc",
        gesture: "point",
        say: "R zero se two tak. Window abc. Set {a,b,c}. Best = 3. Abhi sab clean.",
        sayEn: "R from 0 to 2. Window abc. Set {a,b,c}. Best = 3. All clean so far.",
        sayHi: "R 0 से 2 तक। विंडो abc। सेट {a,b,c}। बेस्ट = 3। अभी सब क्लीन।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        pointers: { L: 0, R: 2 },
        window: [0, 2],
        hi: [0, 1, 2],
        map: { a: 1, b: 1, c: 1 },
        stats: { best: 3 },
      },
      {
        chapter: "Dry run",
        board: "Duplicate a at R=3",
        gesture: "write",
        say: "R=3 pe 'a' dubara. Purana 'a' index 0 pe tha. L ko 1 pe le jao. Window bca… nahi bc a.",
        sayEn: "At R=3, 'a' repeats. Old 'a' was at 0. Move L to 1. Window becomes b, c, a.",
        sayHi: "R=3 पर 'a' दोबारा। पुराना 'a' 0 पर। L को 1 पर। विंडो b,c,a।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        pointers: { L: 1, R: 3 },
        window: [1, 3],
        hi: [1, 2, 3],
        map: { b: 1, c: 1, a: 1 },
        stats: { best: 3, action: "shrink L" },
      },
      {
        chapter: "Dry run",
        board: "Scan continues",
        gesture: "point",
        say: "Aage bhi same dance. Har char max ek baar enter/leave. Best kabhi 3 se upar nahi yahan.",
        sayEn: "Same dance ahead. Each char enters/leaves at most once. Best never exceeds 3 here.",
        sayHi: "आगे भी वही डांस। हर char अधिकतम एक बार अंदर/बाहर। बेस्ट यहाँ 3 से ऊपर नहीं।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        window: [2, 4],
        pointers: { L: 2, R: 4 },
        hi: [2, 3, 4],
        stats: { best: 3 },
      },
      {
        chapter: "Wrap",
        board: "Answer 3",
        gesture: "celebrate",
        say: "Jawab 3. O(n) time kyunki L aur R sirf aage badhte hain. Ab tum code likho.",
        sayEn: "Answer is 3. O(n) time because L and R only move forward. Now you write the code.",
        sayHi: "जवाब 3। O(n) टाइम क्योंकि L और R सिर्फ आगे बढ़ते हैं। अब तुम कोड लिखो।",
        cells: ["a", "b", "c", "a", "b", "c", "b", "b"],
        hi: [0, 1, 2],
        stats: { answer: 3, time: "O(n)" },
        codeLine: "return best;",
      },
    ],
  },
  "kadane-show": {
    id: "kadane-show",
    title: "Kadane — Maximum Subarray",
    subtitle: "Running sum vs restart — the classic DP one-liner intuition.",
    kind: "kadane",
    durationHint: "~2 min",
    practiceIds: ["maximum-subarray"],
    steps: [
      {
        chapter: "Hook",
        board: "Maximum Subarray",
        gesture: "explain",
        say: "Suno. Array mein numbers hain. Continuous subarray ka max sum chahiye. Empty nahi — kam se kam ek element.",
        sayEn: "Listen. You get an array. Find the max sum of a contiguous subarray. At least one element.",
        sayHi: "सुनो। ऐरे में नंबर हैं। लगातार सबऐरे का मैक्स सम चाहिए। कम से कम एक एलिमेंट।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        stats: { ask: "max contiguous sum?" },
      },
      {
        chapter: "Contract",
        board: "One contiguous block",
        gesture: "point",
        say: "Subarray ek piece honi chahiye — beech mein gap nahi. Yahan jawab 6 wala block [4,-1,2,1].",
        sayEn: "Subarray is one contiguous piece — no gaps. Here answer 6 comes from [4,-1,2,1].",
        sayHi: "सबऐरे एक टुकड़ा — बीच में गैप नहीं। यहाँ जवाब 6 — ब्लॉक [4,-1,2,1]।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        hi: [3, 4, 5, 6],
        stats: { return: "int sum" },
      },
      {
        chapter: "Wrong path",
        board: "All subarrays O(n²)",
        gesture: "think",
        say: "Har subarray ka sum nikal lo. Chalega. Par slow. Kadane ek pass mein karta hai.",
        sayEn: "Sum every subarray. Works. But slow. Kadane does it in one pass.",
        sayHi: "हर सबऐरे का सम। चलेगा। पर धीमा। Kadane एक पास में।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        stats: { brute: "O(n²)", avoid: "nested loops" },
      },
      {
        chapter: "The idea",
        board: "cur = running sum",
        gesture: "write",
        say: "Idea. cur rakho — abhi wali subarray ka sum ending at i. best global max.",
        sayEn: "Idea. Keep cur — sum of subarray ending at i. best is global max.",
        sayHi: "आइडिया। cur — i पर खत्म होने वाली सबऐरे का सम। best ग्लोबल मैक्स।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        stats: { cur: "ending here", best: "global" },
        codeLine: "int cur = nums[0], best = nums[0];",
      },
      {
        chapter: "The trick",
        board: "Extend or restart",
        gesture: "explain",
        say: "Trick. Har step: ya to cur mein nums[i] jod do, ya fresh start nums[i]. Jo bada woh lo.",
        sayEn: "Trick. Each step: extend cur with nums[i], or restart at nums[i]. Take the larger.",
        sayHi: "ट्रिक। हर स्टेप: cur में nums[i] जोड़ो, या nums[i] से नया। जो बड़ा वो लो।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        stats: { rule: "cur = max(x, cur+x)" },
        codeLine: "cur = max(nums[i], cur + nums[i]); best = max(best, cur);",
      },
      {
        chapter: "Dry run",
        board: "i = 0 · cur -2",
        gesture: "point",
        say: "Index zero. Value -2. cur = -2, best = -2. Negative start — theek, aage fix hoga.",
        sayEn: "Index 0. Value -2. cur = -2, best = -2. Negative start — fine, fixes ahead.",
        sayHi: "इंडेक्स 0। वैल्यू -2। cur = -2, best = -2। नेगेटिव स्टार्ट — आगे ठीक।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        hi: [0],
        pointers: { i: 0 },
        stats: { cur: -2, best: -2 },
      },
      {
        chapter: "Dry run",
        board: "i = 1 · restart",
        gesture: "write",
        say: "Index one. -2+1 = -1, sirf 1 better. cur = 1. Restart jeeta. best = 1.",
        sayEn: "Index 1. -2+1 = -1, but 1 alone is better. cur = 1. Restart wins. best = 1.",
        sayHi: "इंडेक्स 1। -2+1 = -1, सिर्फ 1 बेहतर। cur = 1। रीस्टार्ट जीता। best = 1।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        hi: [1],
        pointers: { i: 1 },
        stats: { cur: 1, best: 1, choice: "restart" },
      },
      {
        chapter: "Dry run",
        board: "Peak at 6",
        gesture: "celebrate",
        say: "Index three se grow: 4, phir 4-1+2+1 = 6. best = 6. Yahi final answer.",
        sayEn: "From index 3: 4, then 4-1+2+1 = 6. best = 6. That is the final answer.",
        sayHi: "इंडेक्स 3 से: 4, फिर 4-1+2+1 = 6। best = 6। यही फाइनल जवाब।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        hi: [3, 4, 5, 6],
        window: [3, 6],
        pointers: { i: 6 },
        stats: { cur: 6, best: 6 },
        codeLine: "return best; // 6",
      },
      {
        chapter: "Wrap",
        board: "Kadane done",
        gesture: "celebrate",
        say: "Bas. Ek line loop. O(n) time, O(1) space. Extend ya restart — yaad rakhna. Ab likho.",
        sayEn: "Done. One loop. O(n) time, O(1) space. Extend or restart — remember that. Now write it.",
        sayHi: "बस। एक लूप। O(n) टाइम, O(1) स्पेस। एक्सटेंड या रीस्टार्ट। अब लिखो।",
        cells: [-2, 1, -3, 4, -1, 2, 1, -5, 4],
        hi: [3, 4, 5, 6],
        stats: { answer: 6, time: "O(n)" },
      },
    ],
  },
  "move-zeroes-show": {
    id: "move-zeroes-show",
    title: "Move Zeroes — Write Pointer",
    subtitle: "Slow pointer writes non-zeros; rest fill with 0.",
    kind: "two-pointers",
    durationHint: "~2 min",
    practiceIds: ["move-zeroes"],
    steps: [
      {
        chapter: "Hook",
        board: "Move Zeroes",
        gesture: "explain",
        say: "Suno. Array mein zero aur non-zero mix hai. Saare zero end mein, order same rakho — in-place.",
        sayEn: "Listen. Array mixes zeros and non-zeros. Move all zeros to the end, keep order — in-place.",
        sayHi: "सुनो। ऐरे में ज़ीरो और नॉन-ज़ीरो मिक्स। सारे ज़ीरो अंत में, ऑर्डर same — इन-प्लेस।",
        cells: [0, 1, 0, 3, 12],
        stats: { ask: "zeros to back" },
      },
      {
        chapter: "Contract",
        board: "In-place, stable order",
        gesture: "point",
        say: "Extra array nahi. Non-zeros ka relative order change nahi. [0,1,0,3,12] → [1,3,12,0,0].",
        sayEn: "No extra array. Relative order of non-zeros unchanged. [0,1,0,3,12] → [1,3,12,0,0].",
        sayHi: "एक्स्ट्रा ऐरे नहीं। नॉन-ज़ीरो का ऑर्डर same। [0,1,0,3,12] → [1,3,12,0,0]।",
        cells: [0, 1, 0, 3, 12],
        stats: { return: "void in-place" },
      },
      {
        chapter: "Wrong path",
        board: "Sort or count zeros",
        gesture: "think",
        say: "Sort kar do? Order bigad jata hai. Count zeros phir rewrite — do pass. Write pointer ek pass.",
        sayEn: "Sort? Order breaks. Count zeros then rewrite — two passes. Write pointer is one pass.",
        sayHi: "सॉर्ट? ऑर्डर बिगड़ेगा। ज़ीरो काउंट फिर राइट — दो पास। राइट पॉइंटर एक पास।",
        cells: [0, 1, 0, 3, 12],
        stats: { avoid: "sort / double scan" },
      },
      {
        chapter: "The idea",
        board: "write = next slot",
        gesture: "write",
        say: "Idea. write pointer batata hai agla non-zero kahan likhna. read har element scan karta hai.",
        sayEn: "Idea. write pointer is where the next non-zero goes. read scans every element.",
        sayHi: "आइडिया। write अगला नॉन-ज़ीरो कहाँ लिखना। read हर एलिमेंट स्कैन।",
        cells: [0, 1, 0, 3, 12],
        pointers: { write: 0, read: 0 },
        codeLine: "int w = 0;",
      },
      {
        chapter: "The trick",
        board: "Swap or assign",
        gesture: "explain",
        say: "Trick. Agar nums[read] != 0, nums[write] = nums[read], write++. Zero ko skip — baad mein tail zero fill.",
        sayEn: "Trick. If nums[read] != 0, nums[write] = nums[read], write++. Skip zeros — fill tail with zeros after.",
        sayHi: "ट्रिक। अगर nums[read] != 0, nums[write] = nums[read], write++। ज़ीरो स्किप — बाद में टेल ज़ीरो।",
        cells: [0, 1, 0, 3, 12],
        stats: { rule: "nonzero → write++" },
        codeLine: "if (nums[r]) nums[w++] = nums[r];",
      },
      {
        chapter: "Dry run",
        board: "read=1 · write 1",
        gesture: "point",
        say: "read index one pe value 1. Zero nahi. nums[0] = 1. write ab 1.",
        sayEn: "read at index 1, value 1. Not zero. nums[0] = 1. write is now 1.",
        sayHi: "read इंडेक्स 1, वैल्यू 1। ज़ीरो नहीं। nums[0] = 1। write अब 1।",
        cells: [1, 1, 0, 3, 12],
        pointers: { write: 1, read: 1 },
        hi: [0],
        stats: { action: "placed 1" },
      },
      {
        chapter: "Dry run",
        board: "Place 3 and 12",
        gesture: "write",
        say: "read aage: 0 skip, 3 likho index 1, 12 index 2. write = 3.",
        sayEn: "read ahead: skip 0, write 3 at index 1, 12 at index 2. write = 3.",
        sayHi: "read आगे: 0 स्किप, 3 इंडेक्स 1, 12 इंडेक्स 2। write = 3।",
        cells: [1, 3, 12, 3, 12],
        pointers: { write: 3, read: 4 },
        hi: [0, 1, 2],
        stats: { prefix: "[1,3,12]" },
      },
      {
        chapter: "Dry run",
        board: "Zero-fill tail",
        gesture: "celebrate",
        say: "write se end tak zero bhar do. Final [1,3,12,0,0]. Done!",
        sayEn: "Fill from write to end with zeros. Final [1,3,12,0,0]. Done!",
        sayHi: "write से अंत तक ज़ीरो भरो। फाइनल [1,3,12,0,0]। डन!",
        cells: [1, 3, 12, 0, 0],
        hi: [0, 1, 2, 3, 4],
        pointers: { write: 3 },
        stats: { answer: "[1,3,12,0,0]" },
        codeLine: "while (w < n) nums[w++] = 0;",
      },
      {
        chapter: "Wrap",
        board: "One pass",
        gesture: "celebrate",
        say: "O(n) ek scan. Write pointer pattern bahut problems mein aata hai. Ab tum likho.",
        sayEn: "O(n) one scan. Write pointer pattern appears in many problems. Now you write it.",
        sayHi: "O(n) एक स्कैन। राइट पॉइंटर पैटर्न कई प्रॉब्लम्स में। अब तुम लिखो।",
        cells: [1, 3, 12, 0, 0],
        stats: { time: "O(n)", space: "O(1)" },
      },
    ],
  },
  "binary-search-intro": {
    id: "binary-search-intro",
    title: "Binary Search — Halve the World",
    subtitle: "Sorted array pe O(log n) — interview ka bread-butter.",
    kind: "two-pointers",
    durationHint: "~2 min",
    practiceIds: ["binary-search", "search-insert"],
    steps: [
      {
        chapter: "Hook",
        board: "Binary Search",
        gesture: "explain",
        say: "Suno. Sorted array hai. Target number dhundho. Linear scan slow — har step space aadha karo.",
        sayEn: "Listen. Sorted array. Find the target. Linear scan is slow — halve the search space each step.",
        sayHi: "सुनो। सॉर्टेड ऐरे। टारगेट ढूँढो। लीनियर स्कैन धीमा — हर स्टेप स्पेस आधा।",
        cells: [1, 3, 5, 7, 9, 11],
        stats: { target: 7, ask: "index of 7?" },
      },
      {
        chapter: "Contract",
        board: "Sorted ascending",
        gesture: "point",
        say: "Array sorted hona zaroori. Return index agar mile, warna -1. Search-insert mein insert position bhi yahi idea.",
        sayEn: "Array must be sorted. Return index if found, else -1. Search-insert uses the same idea for position.",
        sayHi: "ऐरे सॉर्टेड ज़रूरी। मिले तो इंडेक्स, नहीं तो -1। सर्च-इन्सर्ट भी यही आइडिया।",
        cells: [1, 3, 5, 7, 9, 11],
        stats: { return: "index or -1" },
      },
      {
        chapter: "Wrong path",
        board: "Linear scan O(n)",
        gesture: "think",
        say: "Left se right scan. Chalega. Par million elements? Binary O(log n) — seconds vs minutes feel.",
        sayEn: "Scan left to right. Works. But a million elements? Binary is O(log n).",
        sayHi: "बाएँ से दाएँ स्कैन। चलेगा। पर लाखों एलिमेंट? बाइनरी O(log n)।",
        cells: [1, 3, 5, 7, 9, 11],
        stats: { avoid: "O(n) scan" },
      },
      {
        chapter: "The idea",
        board: "L, R, mid",
        gesture: "write",
        say: "Idea. L start, R end. mid = beech. Compare nums[mid] with target. Ek half discard.",
        sayEn: "Idea. L at start, R at end. mid in the middle. Compare nums[mid] to target. Discard one half.",
        sayHi: "आइडिया। L शुरू, R अंत। mid बीच। nums[mid] vs टारगेट। एक हाफ़ काटो।",
        cells: [1, 3, 5, 7, 9, 11],
        pointers: { L: 0, R: 5 },
        window: [0, 5],
        codeLine: "while (L <= R) { int mid = L + (R - L) / 2; }",
      },
      {
        chapter: "The trick",
        board: "Three-way compare",
        gesture: "explain",
        say: "Trick. Equal → return mid. Chhota → L = mid+1. Bada → R = mid-1. Loop jab tak L <= R.",
        sayEn: "Trick. Equal → return mid. Too small → L = mid+1. Too big → R = mid-1. Loop while L <= R.",
        sayHi: "ट्रिक। बराबर → mid रिटर्न। छोटा → L = mid+1। बड़ा → R = mid-1। L <= R तक।",
        cells: [1, 3, 5, 7, 9, 11],
        stats: { rule: "< → L=mid+1, > → R=mid-1" },
        codeLine: "if (nums[mid] == target) return mid;",
      },
      {
        chapter: "Dry run",
        board: "mid=2 · value 5",
        gesture: "point",
        say: "Pehla mid index 2, value 5. Target 7 bada hai. Left half including 5 useless. L = 3.",
        sayEn: "First mid index 2, value 5. Target 7 is larger. Left half including 5 is useless. L = 3.",
        sayHi: "पहला mid 2, वैल्यू 5। टारगेट 7 बड़ा। बायाँ हाफ़ काट। L = 3।",
        cells: [1, 3, 5, 7, 9, 11],
        pointers: { L: 3, R: 5, mid: 2 },
        hi: [2],
        window: [3, 5],
        stats: { midVal: 5, action: "go right" },
      },
      {
        chapter: "Dry run",
        board: "mid=4 · too big",
        gesture: "write",
        say: "Ab L=3, R=5. mid=4, value 9. Target chhota. R = mid-1 = 3.",
        sayEn: "Now L=3, R=5. mid=4, value 9. Target smaller. R = mid-1 = 3.",
        sayHi: "L=3, R=5। mid=4, वैल्यू 9। टारगेट छोटा। R = 3।",
        cells: [1, 3, 5, 7, 9, 11],
        pointers: { L: 3, R: 3, mid: 4 },
        hi: [4],
        window: [3, 3],
        stats: { midVal: 9, action: "go left" },
      },
      {
        chapter: "Dry run",
        board: "Found index 3",
        gesture: "celebrate",
        say: "L=R=3. mid=3, nums[3]=7. Match! Return 3.",
        sayEn: "L=R=3. mid=3, nums[3]=7. Match! Return 3.",
        sayHi: "L=R=3। mid=3, nums[3]=7। मैच! रिटर्न 3।",
        cells: [1, 3, 5, 7, 9, 11],
        pointers: { L: 3, R: 3, mid: 3 },
        hi: [3],
        stats: { found: "index 3" },
        codeLine: "return mid;",
      },
      {
        chapter: "Wrap",
        board: "O(log n)",
        gesture: "celebrate",
        say: "Har step space aadha. Overflow se bachne ke liye L+(R-L)/2. Bread-and-butter skill — ab likho.",
        sayEn: "Each step halves space. Use L+(R-L)/2 to avoid overflow. Bread-and-butter skill — now write it.",
        sayHi: "हर स्टेप स्पेस आधा। L+(R-L)/2 ओवरफ्लो से बचाव। अब लिखो।",
        cells: [1, 3, 5, 7, 9, 11],
        hi: [3],
        stats: { answer: 3, time: "O(log n)" },
      },
    ],
  },
  "stack-valid-parens": {
    id: "stack-valid-parens",
    title: "Valid Parentheses — Stack Story",
    subtitle: "Open push, close match-top. Empty at end = valid.",
    kind: "array-scan",
    durationHint: "~2 min",
    practiceIds: ["valid-parentheses"],
    steps: [
      {
        chapter: "Hook",
        board: "Valid Parentheses",
        gesture: "explain",
        say: "Suno. String mein brackets hain — (), [], {}. Kya har open ka sahi close hai, order sahi?",
        sayEn: "Listen. String has brackets — (), [], {}. Does every open have a correct close in order?",
        sayHi: "सुनो। स्ट्रिंग में ब्रैकेट्स — (), [], {}। क्या हर ओपन का सही क्लोज, ऑर्डर सही?",
        cells: ["(", ")", "[", "]", "{", "}"],
        stats: { ask: "valid nesting?" },
      },
      {
        chapter: "Contract",
        board: "Return bool",
        gesture: "point",
        say: "True agar poori string valid. False agar mismatch ya extra open. Example ()[]{} → true.",
        sayEn: "True if the whole string is valid. False on mismatch or leftover opens. ()[]{} → true.",
        sayHi: "ट्रू अगर पूरी स्ट्रिंग वैलिड। मिसमैच या एक्स्ट्रा ओपन → फॉल्स। ()[]{} → ट्रू।",
        cells: ["(", ")", "[", "]", "{", "}"],
        stats: { return: "true / false" },
      },
      {
        chapter: "Wrong path",
        board: "Count only",
        gesture: "think",
        say: "Sirf count open/close? Order miss ho jata hai — (] galat count se pass ho sakta. Stack chahiye.",
        sayEn: "Just count opens and closes? Order is lost — (] might pass. You need a stack.",
        sayHi: "सिर्फ काउंट? ऑर्डर मिस — (] गलत पास हो सकता। स्टैक चाहिए।",
        cells: ["(", "]", "[", ")"],
        stats: { avoid: "count-only" },
      },
      {
        chapter: "The idea",
        board: "Stack of opens",
        gesture: "write",
        say: "Idea. Stack rakho. Open bracket aaye → push. Close aaye → top match karo, pop.",
        sayEn: "Idea. Keep a stack. Open bracket → push. Close → match top, pop.",
        sayHi: "आइडिया। स्टैक रखो। ओपन → पुश। क्लोज → टॉप मैच, पॉप।",
        cells: ["(", ")", "[", "]", "{", "}"],
        stats: { stack: "empty" },
        codeLine: "stack<char> st;",
      },
      {
        chapter: "The trick",
        board: "Match map",
        gesture: "explain",
        say: "Trick. Close pe stack khali? false. Top partner nahi? false. Match ho to pop. End pe stack khali honi chahiye.",
        sayEn: "Trick. Close but stack empty? false. Top not a partner? false. Else pop. End with empty stack.",
        sayHi: "ट्रिक। क्लोज पर स्टैक खाली? फॉल्स। टॉप पार्टनर नहीं? फॉल्स। पॉप। अंत में स्टैक खाली।",
        cells: ["(", ")", "[", "]", "{", "}"],
        stats: { pairs: "() [] {}" },
        codeLine: "if (st.empty() || st.top() != openFor(c)) return false;",
      },
      {
        chapter: "Dry run",
        board: "Push (",
        gesture: "point",
        say: "i=0 char '('. Stack khali thi. Push. Stack ab [ ( ].",
        sayEn: "i=0 char '('. Stack was empty. Push. Stack is now [ ( ].",
        sayHi: "i=0 '('. स्टैक खाली। पुश। स्टैक [ ( ]।",
        cells: ["(", ")", "[", "]", "{", "}"],
        pointers: { i: 0 },
        hi: [0],
        stats: { stack: "[ ( ]", action: "push" },
      },
      {
        chapter: "Dry run",
        board: "Pop match )",
        gesture: "write",
        say: "i=1 char ')'. Top '(' partner hai. Pop. Stack empty. Ab tak valid.",
        sayEn: "i=1 char ')'. Top '(' is partner. Pop. Stack empty. Valid so far.",
        sayHi: "i=1 ')'. टॉप '(' पार्टनर। पॉप। स्टैक खाली। अभी वैलिड।",
        cells: ["(", ")", "[", "]", "{", "}"],
        pointers: { i: 1 },
        hi: [0, 1],
        stats: { stack: "[]", action: "pop match" },
      },
      {
        chapter: "Dry run",
        board: "Finish [] {}",
        gesture: "celebrate",
        say: "Baaki [] aur {} same story. End pe stack khali → return true.",
        sayEn: "Rest of [] and {} same story. Empty stack at end → return true.",
        sayHi: "बाकी [] और {} वही। अंत में स्टैक खाली → ट्रू।",
        cells: ["(", ")", "[", "]", "{", "}"],
        hi: [0, 1, 2, 3, 4, 5],
        pointers: { i: 5 },
        stats: { stack: "[]", answer: "true" },
        codeLine: "return st.empty();",
      },
      {
        chapter: "Wrap",
        board: "Stack wins",
        gesture: "celebrate",
        say: "O(n) ek pass. Open push, close pop-check. Interview favorite — ab tum likho.",
        sayEn: "O(n) one pass. Open push, close pop-check. Interview favorite — now you write it.",
        sayHi: "O(n) एक पास। ओपन पुश, क्लोज पॉप-चेक। इंटरव्यू फेवरेट — अब तुम लिखो।",
        cells: ["(", ")", "[", "]", "{", "}"],
        stats: { answer: "true", time: "O(n)" },
      },
    ],
  },
};

export function getTeacherShow(id: string) {
  return teacherShows[id] || EXTRA_SHOWS[id];
}

export function allTeacherShows() {
  return [...Object.values(teacherShows), ...Object.values(EXTRA_SHOWS)];
}

/** Map problem id → default show */
export const problemShowMap: Record<string, string> = {
  "two-sum": "two-sum-show",
  "two-sum-hash": "two-sum-show",
  "container-most-water": "two-pointers-water",
  "longest-substr-no-repeat": "sliding-window-unique",
  "maximum-subarray": "kadane-show",
  "move-zeroes": "move-zeroes-show",
  "binary-search": "binary-search-intro",
  "search-insert": "binary-search-intro",
  "valid-parentheses": "stack-valid-parens",
  ...PROBLEM_SHOW_EXTRA,
};

Object.assign(teacherShows, EXTRA_SHOWS);
