import { recipeShow } from "./wave3-full.mjs";

/** Remaining wave-3 shows (squares … max-consec-iii) */
export const WAVE3B = [
  recipeShow({
    id: "squares-sorted-show",
    title: "Squares of Sorted Array — Merge Ends",
    subtitle: "Compare abs ends; place larger square from the back.",
    kind: "two-pointers",
    practiceIds: ["squares-sorted"],
    cells: [-4, -1, 0, 3, 10],
    hookBoard: "Sorted Squares",
    hookSay: "Suno. Sorted array ke squares bhi sorted order mein chahiye.",
    hookEn: "Listen. Return the squares of a sorted array, also sorted.",
    hookHi: "सुनो। सॉर्टेड ऐरे के स्क्वेयर्स भी सॉर्टेड ऑर्डर में चाहिए।",
    hookStats: { ask: "sorted squares" },
    contractBoard: "O(n) not n log n",
    contractSay: "Square karke sort O(n log n). Two pointers O(n) better.",
    contractEn: "Square then sort is O(n log n). Two pointers O(n) is better.",
    contractHi: "स्क्वेयर करके सॉर्ट O(n log n)। टू पॉइंटर्स O(n) बेहतर।",
    contractExtra: { stats: { goal: "[0,1,9,16,100]" } },
    wrongBoard: "Map then sort",
    wrongSay: "Har value square, phir sort. Easy par slow-ish for interview flex.",
    wrongEn: "Square every value, then sort. Easy but weaker interview flex.",
    wrongHi: "हर वैल्यू स्क्वेयर, फिर सॉर्ट। आसान पर कमज़ोर फ्लेक्स।",
    wrongExtra: { stats: { avoid: "sort squares" } },
    ideaBoard: "L and R abs",
    ideaSay: "Negatives ke squares bade ho sakte. Ends compare, result peeche se bharao.",
    ideaEn: "Negative squares can be large. Compare ends, fill result from the back.",
    ideaHi: "नेगेटिव स्क्वेयर्स बड़े हो सकते। एंड्स कम्पेयर, रिजल्ट पीछे से भरो।",
    ideaExtra: { pointers: { L: 0, R: 4 }, codeLine: "int L=0,R=n-1,k=n-1;" },
    trickBoard: "Larger abs wins",
    trickSay: "abs(L) > abs(R) → L ka square peeche, L++. Else R ka, R--.",
    trickEn: "If abs(L) > abs(R), place L's square at back, L++. Else R's, R--.",
    trickHi: "अगर abs(L) > abs(R), L का स्क्वेयर पीछे, L++। वरना R का, R--।",
    trickExtra: { codeLine: "if (abs(nums[L]) > abs(nums[R])) ..." },
    dry: [
      { board: "100 first", say: "|-4|=4 < 10. Place 100 at end. R--.", sayEn: "|-4|=4 < 10. Place 100 at end. R--.", sayHi: "|-4|=4 < 10। अंत में 100। R--।", cells: [-4, -1, 0, 3, 10], hi: [4], pointers: { L: 0, R: 3, k: 4 }, stats: { wrote: 100 }, gesture: "write" },
      { board: "16 next", say: "|-4|=4 > 3. Place 16. L++. Phir 9,1,0.", sayEn: "|-4|=4 > 3. Place 16. L++. Then 9,1,0.", sayHi: "|-4|=4 > 3। 16 रखो। L++। फिर 9,1,0।", cells: [0, 1, 9, 16, 100], hi: [3, 4], stats: { progress: "filling" } },
      { board: "Done", say: "Result [0,1,9,16,100]. O(n) merge.", sayEn: "Result [0,1,9,16,100]. O(n) merge.", sayHi: "रिजल्ट [0,1,9,16,100]। O(n) मर्ज।", cells: [0, 1, 9, 16, 100], hi: [0, 1, 2, 3, 4], stats: { answer: "[0,1,9,16,100]" }, gesture: "celebrate" },
    ],
    wrapBoard: "Squares merged",
    wrapSay: "Ends se merge. Ab tum code likho.",
    wrapEn: "Merge from the ends. Now you write the code.",
    wrapHi: "एंड्स से मर्ज। अब तुम कोड लिखो।",
    wrapExtra: { cells: [0, 1, 9, 16, 100], stats: { time: "O(n)" } },
  }),

  recipeShow({
    id: "trapping-rain-show",
    title: "Trapping Rain Water — Two Maxes",
    subtitle: "Water at i = min(leftMax,rightMax) − height[i].",
    kind: "two-pointers",
    practiceIds: ["trapping-rain"],
    cells: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1],
    hookBoard: "Trapping Rain Water",
    hookSay: "Suno. Bars ke beech kitna paani rukega? Hard classic.",
    hookEn: "Listen. How much water can the elevation bars trap? Hard classic.",
    hookHi: "सुनो। बार्स के बीच कितना पानी रुकेगा? हार्ड क्लासिक।",
    hookStats: { ask: "total water units" },
    contractBoard: "Sum of trapped units",
    contractSay: "Har index pe water = max(0, min(Lmax,Rmax)-h[i]). Total sum.",
    contractEn: "Water at each index = max(0, min(Lmax,Rmax)-h[i]). Sum them.",
    contractHi: "हर इंडेक्स पर पानी = max(0, min(Lmax,Rmax)-h[i])। कुल सम।",
    contractExtra: { stats: { expect: 6 } },
    wrongBoard: "For each i scan both sides",
    wrongSay: "Har i pe left/right max alag scan? O(n²). Two pointers O(n).",
    wrongEn: "Per-index left/right max scans? O(n²). Two pointers O(n).",
    wrongHi: "हर i पर लेफ्ट/राइट मैक्स स्कैन? O(n²)। टू पॉइंटर्स O(n)।",
    wrongExtra: { stats: { avoid: "O(n²)" } },
    ideaBoard: "L and R max chase",
    ideaSay: "L aur R ends se. Jo side ka max chhota, wahan water add karke move.",
    ideaEn: "L and R from ends. Move the side with smaller max; add water there.",
    ideaHi: "L और R एंड्स से। जिस साइड का मैक्स छोटा, वहाँ पानी जोड़कर मूव।",
    ideaExtra: { pointers: { L: 0, R: 11 }, codeLine: "int L=0,R=n-1,lMax=0,rMax=0,ans=0;" },
    trickBoard: "Move smaller max side",
    trickSay: "Agar lMax < rMax, L pe water = lMax-h[L], L++. Mirror for R.",
    trickEn: "If lMax < rMax, water at L = lMax-h[L], L++. Mirror for R.",
    trickHi: "अगर lMax < rMax, L पर पानी = lMax-h[L], L++। R के लिए मिरर।",
    trickExtra: { codeLine: "if (lMax < rMax) { ans += lMax - height[L++]; }" },
    dry: [
      { board: "Valley fills", say: "Beech ke 0s aur 1s pe paani bhar-ta. Running total badhta.", sayEn: "Valleys at the 0s and 1s fill with water. Running total grows.", sayHi: "बीच के 0s और 1s पर पानी भरता। टोटल बढ़ता।", hi: [2, 4, 5, 6], pointers: { L: 2, R: 10 }, stats: { water: "accumulating" } },
      { board: "Total 6", say: "Poora dry run ke baad ans=6. Classic answer.", sayEn: "After the full dry run ans=6. Classic answer.", sayHi: "पूरे ड्राई रन के बाद ans=6। क्लासिक जवाब।", hi: [2, 4, 5, 6, 9], stats: { answer: 6 }, gesture: "celebrate" },
      { board: "Pattern lock", say: "min(leftMax,rightMax) intuition yaad rakhna.", sayEn: "Lock the min(leftMax,rightMax) intuition.", sayHi: "min(leftMax,rightMax) इंट्यूशन याद रखना।", stats: { rule: "min of two maxes" }, gesture: "celebrate" },
    ],
    wrapBoard: "Answer 6",
    wrapSay: "Two pointers + running max. O(n)/O(1). Ab likho.",
    wrapEn: "Two pointers + running max. O(n)/O(1). Now write it.",
    wrapHi: "टू पॉइंटर्स + रनिंग मैक्स। O(n)/O(1)। अब लिखो।",
    wrapExtra: { stats: { answer: 6, time: "O(n)" } },
  }),

  recipeShow({
    id: "find-anagrams-show",
    title: "Find All Anagrams — Sliding Counts",
    subtitle: "Fixed window of |p|; record start index on match.",
    kind: "sliding-window",
    practiceIds: ["find-anagrams"],
    cells: ["c", "b", "a", "e", "b", "a", "b", "a", "c", "d"],
    hookBoard: "Find Anagrams",
    hookSay: "Suno. s mein p ke saare anagram windows ke start indexes.",
    hookEn: "Listen. All start indexes in s where a window is an anagram of p.",
    hookHi: "सुनो। s में p के सारे एनाग्राम विंडोज़ के स्टार्ट इंडेक्स।",
    hookStats: { p: "abc", ask: "start indexes" },
    contractBoard: "List of starts",
    contractSay: "p=abc, s=cbaebabacd → starts 0 aur 6.",
    contractEn: "p=abc, s=cbaebabacd → starts 0 and 6.",
    contractHi: "p=abc, s=cbaebabacd → स्टार्ट्स 0 और 6।",
    contractExtra: { stats: { expect: "0 6" } },
    wrongBoard: "Sort each window",
    wrongSay: "Har window sort karke compare? Slow. Freq maps slide O(n).",
    wrongEn: "Sort each window to compare? Slow. Sliding freq maps are O(n).",
    wrongHi: "हर विंडो सॉर्ट कम्पेयर? धीमा। स्लाइडिंग फ़्रीक O(n)।",
    wrongExtra: { stats: { avoid: "sort windows" } },
    ideaBoard: "Window = |p|",
    ideaSay: "p ki need freq. s pe fixed window. Slide: add R, remove L.",
    ideaEn: "Need freq from p. Fixed window on s. Slide: add R, remove L.",
    ideaHi: "p की नीड फ़्रीक। s पर फिक्स्ड विंडो। स्लाइड: R ऐड, L रिमूव।",
    ideaExtra: { window: [0, 2], map: { a: 1, b: 1, c: 1 }, codeLine: "int need[26], win[26];" },
    trickBoard: "Record on match",
    trickSay: "Jab counts match, start = R-|p|+1 push. Permutation-string jaisa.",
    trickEn: "When counts match, push start = R-|p|+1. Same DNA as permutation-in-string.",
    trickHi: "जब काउंट्स मैच, स्टार्ट = R-|p|+1 पुश। परम्यूटेशन-स्ट्रिंग जैसा।",
    trickExtra: { codeLine: "if (match) ans.push_back(i - m + 1);" },
    dry: [
      { board: "Window cba", say: "0..2 'cba' counts = abc. Match! Push 0.", sayEn: "0..2 'cba' counts equal abc. Match! Push 0.", sayHi: "0..2 'cba' काउंट्स = abc। मैच! 0 पुश।", hi: [0, 1, 2], window: [0, 2], pointers: { L: 0, R: 2 }, stats: { found: 0 }, gesture: "celebrate" },
      { board: "Window bac", say: "6..8 'bac' bhi match. Push 6.", sayEn: "6..8 'bac' also matches. Push 6.", sayHi: "6..8 'bac' भी मैच। 6 पुश।", hi: [6, 7, 8], window: [6, 8], pointers: { L: 6, R: 8 }, stats: { found: "0, 6" }, gesture: "celebrate" },
      { board: "Answer", say: "Starts [0,6]. Fixed window + freq done.", sayEn: "Starts [0,6]. Fixed window + freq done.", sayHi: "स्टार्ट्स [0,6]। फिक्स्ड विंडो + फ़्रीक डन।", stats: { answer: "[0, 6]" }, gesture: "celebrate" },
    ],
    wrapBoard: "0 and 6",
    wrapSay: "Anagram hunt = sliding counts. Ab likho.",
    wrapEn: "Anagram hunt = sliding counts. Now write it.",
    wrapHi: "एनाग्राम हंट = स्लाइडिंग काउंट्स। अब लिखो।",
    wrapExtra: { stats: { answer: "0 6", time: "O(n)" } },
  }),

  recipeShow({
    id: "valid-paren-show",
    title: "Valid Parentheses — Stack Story",
    subtitle: "Push opens; on close, top must match; empty at end.",
    kind: "array-scan",
    practiceIds: ["valid-parentheses"],
    cells: ["(", ")", "[", "]", "{", "}"],
    hookBoard: "Valid Parentheses",
    hookSay: "Suno. Brackets sahi balanced hain kya? Stack ki kahani.",
    hookEn: "Listen. Are the brackets correctly balanced? A stack story.",
    hookHi: "सुनो। ब्रैकेट्स सही बैलेंस्ड हैं क्या? स्टैक की कहानी।",
    hookStats: { ask: "valid?" },
    contractBoard: "true / false",
    contractSay: "Types aur order dono matter. ()[]{} true. (] false.",
    contractEn: "Types and order both matter. ()[]{} true. (] false.",
    contractHi: "टाइप्स और ऑर्डर दोनों। ()[]{} ट्रू। (] फॉल्स।",
    contractExtra: { stats: { return: "bool" } },
    wrongBoard: "Counter only",
    wrongSay: "Sirf count++/--? Nested mismatch miss. Stack chahiye.",
    wrongEn: "Only a counter? Misses nested mismatches. You need a stack.",
    wrongHi: "सिर्फ काउंटर? नेस्टेड मिसमैच मिस। स्टैक चाहिए।",
    wrongExtra: { stats: { avoid: "bare counter" } },
    ideaBoard: "stack<char>",
    ideaSay: "Open → push. Close → top se match, pop. End pe empty.",
    ideaEn: "Open → push. Close → must match top, then pop. Empty at end.",
    ideaHi: "ओपन → पुश। क्लोज़ → टॉप से मैच, पॉप। अंत में एम्पटी।",
    ideaExtra: { stats: { stack: "[]" }, codeLine: "stack<char> st;" },
    trickBoard: "Map closes",
    trickSay: "Map: )→(, ]→[, }→{. Close pe empty ya mismatch → false.",
    trickEn: "Map: )→(, ]→[, }→{. Empty or mismatch on close → false.",
    trickHi: "मैप: )→(, ]→[, }→{। क्लोज़ पर एम्पटी या मिसमैच → फॉल्स।",
    trickExtra: { codeLine: "if (st.empty() || st.top()!=need) return false;" },
    dry: [
      { board: "Push (", say: "i=0 '(' push. Stack: [ ( ]", sayEn: "i=0 '(' push. Stack: [ ( ]", sayHi: "i=0 '(' पुश। स्टैक: [ ( ]", hi: [0], pointers: { i: 0 }, stats: { stack: "[ ( ]" }, gesture: "write" },
      { board: "Pop match", say: "i=1 ')' top '(' match → pop. Empty. Good.", sayEn: "i=1 ')' top '(' matches → pop. Empty. Good.", sayHi: "i=1 ')' टॉप '(' मैच → पॉप। एम्पटी। गुड।", hi: [0, 1], pointers: { i: 1 }, stats: { stack: "[]", action: "pop" } },
      { board: "All clear", say: "[] aur {} same. End empty → true.", sayEn: "[] and {} same. End empty → true.", sayHi: "[] और {} वही। अंत एम्पटी → ट्रू।", hi: [0, 1, 2, 3, 4, 5], stats: { answer: "true" }, codeLine: "return st.empty();", gesture: "celebrate" },
    ],
    wrapBoard: "Valid",
    wrapSay: "Stack discipline. Ab tum likho.",
    wrapEn: "Stack discipline. Now you write it.",
    wrapHi: "स्टैक डिसिप्लिन। अब तुम लिखो।",
    wrapExtra: { stats: { answer: "true", time: "O(n)" } },
  }),

  recipeShow({
    id: "daily-temp-show",
    title: "Daily Temperatures — Monotonic Stack",
    subtitle: "Stack of decreasing indexes; pop when a warmer day arrives.",
    kind: "array-scan",
    practiceIds: ["daily-temperatures"],
    cells: [73, 74, 75, 71, 69, 72, 76, 73],
    hookBoard: "Daily Temperatures",
    hookSay: "Suno. Har din — kitne din baad warmer temperature?",
    hookEn: "Listen. For each day — how many days until a warmer temperature?",
    hookHi: "सुनो। हर दिन — कितने दिन बाद गर्म तापमान?",
    hookStats: { ask: "days to warmer" },
    contractBoard: "Distance array",
    contractSay: "Answer array same size. Agar kabhi warmer na aaye, 0.",
    contractEn: "Answer array same size. If no warmer day ever, 0.",
    contractHi: "ऐन्सर ऐरे सेम साइज़। अगर कभी गर्म न आए, 0।",
    contractExtra: { stats: { expect: "1 1 4 2 1 1 0 0" } },
    wrongBoard: "Nested scan forward",
    wrongSay: "Har din aage scan O(n²). Mono stack O(n).",
    wrongEn: "Forward scan per day is O(n²). Mono stack is O(n).",
    wrongHi: "हर दिन आगे स्कैन O(n²)। मोनो स्टैक O(n)।",
    wrongExtra: { stats: { avoid: "O(n²)" } },
    ideaBoard: "Decreasing stack",
    ideaSay: "Stack mein indexes, temperatures decreasing. Warmer aaye to pop.",
    ideaEn: "Stack holds indexes with decreasing temps. Pop when warmer arrives.",
    ideaHi: "स्टैक में इंडेक्स, टेम्प घटते। गर्म आए तो पॉप।",
    ideaExtra: { codeLine: "stack<int> st; // indexes" },
    trickBoard: "Distance = i - st.top()",
    trickSay: "Pop pe ans[top] = i - top. Unresolved end pe 0 rehte.",
    trickEn: "On pop, ans[top] = i - top. Unresolved stay 0 at the end.",
    trickHi: "पॉप पर ans[top] = i - top। अनरिज़ॉल्व्ड अंत में 0।",
    trickExtra: { codeLine: "ans[st.top()] = i - st.top(); st.pop();" },
    dry: [
      { board: "74 warms 73", say: "Day1 74 > 73. ans[0]=1. Stack updates.", sayEn: "Day1 74 > 73. ans[0]=1. Stack updates.", sayHi: "दिन1 74 > 73। ans[0]=1। स्टैक अपडेट।", hi: [0, 1], pointers: { i: 1 }, stats: { "ans[0]": 1 }, gesture: "write" },
      { board: "76 resolves many", say: "76 aata — 69,71,72,75 resolve. Distances fill.", sayEn: "76 arrives — resolves 69,71,72,75. Distances fill.", sayHi: "76 आता — 69,71,72,75 रिज़ॉल्व। डिस्टेंस भरते।", hi: [2, 3, 4, 5, 6], pointers: { i: 6 }, stats: { note: "big warmer" }, gesture: "celebrate" },
      { board: "Final", say: "Answer 1 1 4 2 1 1 0 0. Last two never warmer.", sayEn: "Answer 1 1 4 2 1 1 0 0. Last two never get warmer.", sayHi: "जवाब 1 1 4 2 1 1 0 0। आखिरी दो कभी गर्म नहीं।", cells: [1, 1, 4, 2, 1, 1, 0, 0], stats: { answer: "1 1 4 2 1 1 0 0" }, gesture: "celebrate" },
    ],
    wrapBoard: "Mono stack win",
    wrapSay: "Next greater element pattern. Ab likho.",
    wrapEn: "Next-greater-element pattern. Now write it.",
    wrapHi: "नेक्स्ट-ग्रेटर-एलिमेंट पैटर्न। अब लिखो।",
    wrapExtra: { cells: [1, 1, 4, 2, 1, 1, 0, 0], stats: { time: "O(n)" } },
  }),

  recipeShow({
    id: "reverse-ll-show",
    title: "Reverse Linked List — Three Pointers",
    subtitle: "prev, cur, next — flip each link as you walk.",
    kind: "array-scan",
    practiceIds: ["reverse-linked-list"],
    cells: [1, 2, 3, 4, 5],
    hookBoard: "Reverse Linked List",
    hookSay: "Suno. Singly linked list reverse. Interview ka bread-butter.",
    hookEn: "Listen. Reverse a singly linked list. Interview bread-and-butter.",
    hookHi: "सुनो। सिंगली लिंक्ड लिस्ट रिवर्स। इंटरव्यू का ब्रेड-बटर।",
    hookStats: { ask: "new head" },
    contractBoard: "Return new head",
    contractSay: "1→2→3→4→5 banega 5→4→3→2→1. New head 5.",
    contractEn: "1→2→3→4→5 becomes 5→4→3→2→1. New head is 5.",
    contractHi: "1→2→3→4→5 बनेगा 5→4→3→2→1। नया हेड 5।",
    contractExtra: { stats: { goal: "5 4 3 2 1" } },
    wrongBoard: "Extra array",
    wrongSay: "Values array mein daal reverse? Chalega. Pointer flip cleaner.",
    wrongEn: "Dump values to an array and reverse? Works. Pointer flip is cleaner.",
    wrongHi: "वैल्यूज़ ऐरे में डाल रिवर्स? चलेगा। पॉइंटर फ्लिप क्लीनर।",
    wrongExtra: { stats: { avoid: "value copy" } },
    ideaBoard: "prev cur next",
    ideaSay: "prev=null, cur=head. next bacha ke cur->next=prev. Phir shift.",
    ideaEn: "prev=null, cur=head. Save next, set cur->next=prev. Then shift.",
    ideaHi: "prev=null, cur=head। next बचाके cur->next=prev। फिर शिफ्ट।",
    ideaExtra: { pointers: { prev: -1, cur: 0 }, codeLine: "ListNode *prev=nullptr, *cur=head;" },
    trickBoard: "Save next first",
    trickSay: "Pehle next=cur->next likho, warna chain toot. Phir relink.",
    trickEn: "Save next=cur->next first, or the chain breaks. Then relink.",
    trickHi: "पहले next=cur->next, वरना चेन टूटे। फिर रिलिंक।",
    trickExtra: { codeLine: "auto* nxt=cur->next; cur->next=prev; prev=cur; cur=nxt;" },
    dry: [
      { board: "Flip first", say: "1 ka next null. prev=1, cur=2. Partial reverse shuru.", sayEn: "1's next becomes null. prev=1, cur=2. Partial reverse starts.", sayHi: "1 का नेक्स्ट null। prev=1, cur=2। पार्टल रिवर्स शुरू।", hi: [0], pointers: { prev: 0, cur: 1 }, cells: [1, 2, 3, 4, 5], stats: { links: "1←" }, gesture: "write" },
      { board: "Walk on", say: "Har step ek arrow ulta. Cur null hone tak.", sayEn: "Each step flips one arrow. Until cur is null.", sayHi: "हर स्टेप एक एरो उल्टा। cur null तक।", hi: [0, 1, 2], pointers: { prev: 2, cur: 3 }, stats: { progress: "reversing" } },
      { board: "New head 5", say: "prev=5. Return prev. List 5 4 3 2 1.", sayEn: "prev=5. Return prev. List 5 4 3 2 1.", sayHi: "prev=5। prev रिटर्न। लिस्ट 5 4 3 2 1।", cells: [5, 4, 3, 2, 1], hi: [0], stats: { answer: "5 4 3 2 1" }, codeLine: "return prev;", gesture: "celebrate" },
    ],
    wrapBoard: "Reversed",
    wrapSay: "Teen pointers. Draw once, code forever. Ab likho.",
    wrapEn: "Three pointers. Draw once, code forever. Now write it.",
    wrapHi: "तीन पॉइंटर्स। एक बार ड्रॉ, हमेशा कोड। अब लिखो।",
    wrapExtra: { cells: [5, 4, 3, 2, 1], stats: { time: "O(n)" } },
  }),

  recipeShow({
    id: "merge-lists-show",
    title: "Merge Two Sorted Lists — Dummy Head",
    subtitle: "Always attach the smaller head; stitch leftovers.",
    kind: "array-scan",
    practiceIds: ["merge-two-lists"],
    cells: [1, 2, 4],
    hookBoard: "Merge Two Lists",
    hookSay: "Suno. Do sorted linked lists. Ek sorted list mein merge.",
    hookEn: "Listen. Two sorted linked lists. Merge into one sorted list.",
    hookHi: "सुनो। दो सॉर्टेड लिंक्ड लिस्ट्स। एक सॉर्टेड लिस्ट में मर्ज।",
    hookStats: { list1: "1 2 4", list2: "1 3 4" },
    contractBoard: "New sorted chain",
    contractSay: "Result 1→1→2→3→4→4. Nodes reuse — naya value copy mat.",
    contractEn: "Result 1→1→2→3→4→4. Reuse nodes — do not copy values.",
    contractHi: "रिजल्ट 1→1→2→3→4→4। नोड्स रीयूज़ — वैल्यू कॉपी मत।",
    contractExtra: { stats: { goal: "1 1 2 3 4 4" } },
    wrongBoard: "Build new nodes",
    wrongSay: "Har baar new ListNode? Waste. Existing nodes stitch karo.",
    wrongEn: "New ListNode every time? Waste. Stitch existing nodes.",
    wrongHi: "हर बार नया ListNode? वेस्ट। मौजूदा नोड्स स्टिच करो।",
    wrongExtra: { stats: { avoid: "alloc all" } },
    ideaBoard: "Dummy + tail",
    ideaSay: "Dummy head. Tail se chhota node attach. Edge cases soft.",
    ideaEn: "Dummy head. Attach the smaller node at tail. Softens edge cases.",
    ideaHi: "डमी हेड। टेल से छोटा नोड अटैच। एज केसेस आसान।",
    ideaExtra: { codeLine: "ListNode dummy(0); auto* tail=&dummy;" },
    trickBoard: "Compare heads",
    trickSay: "list1->val <= list2->val? list1 lo. Else list2. Leftover end pe.",
    trickEn: "list1->val <= list2->val? Take list1. Else list2. Attach leftover at end.",
    trickHi: "list1->val <= list2->val? list1 लो। वरना list2। leftover अंत में।",
    trickExtra: { codeLine: "tail->next = list1 ? list1 : list2;" },
    dry: [
      { board: "1 vs 1", say: "Dono 1. Ek lo (list1). Phir dusra 1. Chain: 1→1.", sayEn: "Both 1. Take one (list1). Then the other 1. Chain: 1→1.", sayHi: "दोनों 1। एक लो। फिर दूसरा 1। चेन: 1→1।", cells: [1, 1, 2, 4], hi: [0, 1], stats: { merged: "1,1" }, gesture: "write" },
      { board: "2 vs 3", say: "2 chhota → attach. Phir 3, phir 4s.", sayEn: "2 is smaller → attach. Then 3, then the 4s.", sayHi: "2 छोटा → अटैच। फिर 3, फिर 4s।", cells: [1, 1, 2, 3, 4, 4], hi: [2, 3], stats: { progress: "stitching" } },
      { board: "Done", say: "dummy.next return. 1 1 2 3 4 4.", sayEn: "Return dummy.next. 1 1 2 3 4 4.", sayHi: "dummy.next रिटर्न। 1 1 2 3 4 4।", cells: [1, 1, 2, 3, 4, 4], hi: [0, 1, 2, 3, 4, 5], stats: { answer: "1 1 2 3 4 4" }, codeLine: "return dummy.next;", gesture: "celebrate" },
    ],
    wrapBoard: "Merged lists",
    wrapSay: "Dummy head pattern. Ab likho.",
    wrapEn: "Dummy head pattern. Now write it.",
    wrapHi: "डमी हेड पैटर्न। अब लिखो।",
    wrapExtra: { cells: [1, 1, 2, 3, 4, 4], stats: { time: "O(m+n)" } },
  }),

  recipeShow({
    id: "linked-cycle-show",
    title: "Linked List Cycle — Floyd",
    subtitle: "Slow +1, fast +2; if they meet, there is a cycle.",
    kind: "two-pointers",
    practiceIds: ["linked-list-cycle"],
    cells: [3, 2, 0, -4],
    hookBoard: "Linked List Cycle",
    hookSay: "Suno. List mein cycle hai kya? Floyd tortoise-hare.",
    hookEn: "Listen. Does the list have a cycle? Floyd tortoise and hare.",
    hookHi: "सुनो। लिस्ट में साइकल है क्या? फ्लॉयड टॉरटॉइस-हेयर।",
    hookStats: { pos: 1, ask: "has cycle?" },
    contractBoard: "true / false",
    contractSay: "Cycle → true. Tail null → false. Yahan pos=1 → true.",
    contractEn: "Cycle → true. Tail null → false. Here pos=1 → true.",
    contractHi: "साइकल → ट्रू। टेल null → फॉल्स। यहाँ pos=1 → ट्रू।",
    contractExtra: { stats: { expect: "true" } },
    wrongBoard: "Hash visited nodes",
    wrongSay: "Seen set of pointers. Chalega. O(n) space. Floyd O(1).",
    wrongEn: "Seen set of pointers. Works. O(n) space. Floyd is O(1).",
    wrongHi: "सीन सेट ऑफ़ पॉइंटर्स। चलेगा। O(n) स्पेस। फ्लॉयड O(1)।",
    wrongExtra: { stats: { avoid: "hash nodes" } },
    ideaBoard: "slow & fast",
    ideaSay: "slow ek step, fast do. Cycle mein fast slow ko pakad lega.",
    ideaEn: "slow one step, fast two. In a cycle fast will catch slow.",
    ideaHi: "slow एक स्टेप, fast दो। साइकल में fast slow को पकड़ लेगा।",
    ideaExtra: { pointers: { slow: 0, fast: 0 }, codeLine: "auto *slow=head, *fast=head;" },
    trickBoard: "Meet ⇒ cycle",
    trickSay: "Loop: fast aur fast->next null check. Agar slow==fast → true.",
    trickEn: "Loop: check fast and fast->next null. If slow==fast → true.",
    trickHi: "लूप: fast और fast->next null चेक। अगर slow==fast → ट्रू।",
    trickExtra: { codeLine: "if (slow == fast) return true;" },
    dry: [
      { board: "Start chase", say: "Dono head pe. Phir slow→2, fast→0 (do jumps).", sayEn: "Both at head. Then slow→2, fast→0 (two jumps).", sayHi: "दोनों हेड पर। फिर slow→2, fast→0 (दो जंप)।", hi: [1, 2], pointers: { slow: 1, fast: 2 }, stats: { phase: "chase" } },
      { board: "They meet", say: "Cycle ke andar milte hain. True!", sayEn: "They meet inside the cycle. True!", sayHi: "साइकल के अंदर मिलते हैं। ट्रू!", hi: [1, 3], pointers: { slow: 1, fast: 1 }, stats: { answer: "true" }, codeLine: "return true;", gesture: "celebrate" },
      { board: "No cycle case", say: "Agar fast null pe girе → false. Pattern complete.", sayEn: "If fast hits null → false. Pattern complete.", sayHi: "अगर fast null पर गिरे → फॉल्स। पैटर्न पूरा।", stats: { noCycle: "fast null" }, gesture: "celebrate" },
    ],
    wrapBoard: "Cycle detected",
    wrapSay: "Floyd O(1) space. Ab likho.",
    wrapEn: "Floyd O(1) space. Now write it.",
    wrapHi: "फ्लॉयड O(1) स्पेस। अब लिखो।",
    wrapExtra: { stats: { answer: "true", time: "O(n)" } },
  }),
];
