/** Full course-quality recipes for wave-3 show ids (missing-number … max-consec-iii). */
export function recipeShow(cfg) {
  const {
    id, title, subtitle, kind, practiceIds, durationHint,
    cells, hookSay, hookEn, hookHi, hookBoard, hookStats,
    contractSay, contractEn, contractHi, contractBoard, contractExtra = {},
    wrongSay, wrongEn, wrongHi, wrongBoard, wrongExtra = {},
    ideaSay, ideaEn, ideaHi, ideaBoard, ideaExtra = {},
    trickSay, trickEn, trickHi, trickBoard, trickExtra = {},
    dry,
    wrapSay, wrapEn, wrapHi, wrapBoard, wrapExtra = {},
  } = cfg;

  return {
    id, title, subtitle, kind,
    durationHint: durationHint || "~2 min",
    practiceIds,
    steps: [
      { chapter: "Hook", board: hookBoard, gesture: "explain", say: hookSay, sayEn: hookEn, sayHi: hookHi, cells, stats: hookStats },
      { chapter: "Contract", board: contractBoard, gesture: "point", say: contractSay, sayEn: contractEn, sayHi: contractHi, cells, ...contractExtra },
      { chapter: "Wrong path", board: wrongBoard, gesture: "think", say: wrongSay, sayEn: wrongEn, sayHi: wrongHi, cells, ...wrongExtra },
      { chapter: "The idea", board: ideaBoard, gesture: "write", say: ideaSay, sayEn: ideaEn, sayHi: ideaHi, cells, ...ideaExtra },
      { chapter: "The trick", board: trickBoard, gesture: "explain", say: trickSay, sayEn: trickEn, sayHi: trickHi, cells, ...trickExtra },
      ...dry.map((d, i) => ({
        chapter: "Dry run",
        gesture: d.gesture || (i === dry.length - 1 ? "celebrate" : "point"),
        cells: d.cells || cells,
        ...d,
      })),
      { chapter: "Wrap", board: wrapBoard, gesture: "celebrate", say: wrapSay, sayEn: wrapEn, sayHi: wrapHi, cells: wrapExtra.cells || cells, ...wrapExtra },
    ],
  };
}

export const WAVE3 = [
  recipeShow({
    id: "missing-number-show",
    title: "Missing Number — Sum / XOR",
    subtitle: "n(n+1)/2 minus sum, or XOR all indexes and values.",
    kind: "array-scan",
    practiceIds: ["missing-number"],
    cells: [3, 0, 1],
    hookBoard: "Missing Number",
    hookSay: "Suno. Array size n. Numbers 0 se n tak, ek missing. Kaunsa?",
    hookEn: "Listen. Array of size n. Numbers from 0 to n, one missing. Which?",
    hookHi: "सुनो। ऐरे साइज़ n। नंबर 0 से n तक, एक मिसिंग। कौन सा?",
    hookStats: { n: 3, ask: "which missing?" },
    contractBoard: "Return the missing int",
    contractSay: "Sirf ek number return. Yahan n=3, array [3,0,1], jawab 2.",
    contractEn: "Return exactly one number. Here n=3, array [3,0,1], answer 2.",
    contractHi: "सिर्फ एक नंबर रिटर्न। यहाँ n=3, ऐरे [3,0,1], जवाब 2।",
    contractExtra: { stats: { expect: 2 } },
    wrongBoard: "Sort then scan",
    wrongSay: "Sort karke gap dhundo. Chalega. O(n log n). Better O(n)/O(1) hai.",
    wrongEn: "Sort and find the gap. Works. O(n log n). Better is O(n)/O(1).",
    wrongHi: "सॉर्ट करके गैप ढूँढो। चलेगा। O(n log n)। बेहतर O(n)/O(1) है।",
    wrongExtra: { stats: { avoid: "sort" } },
    ideaBoard: "Expected sum",
    ideaSay: "Idea. 0..n ka sum = n*(n+1)/2. Array ka sum ghatao. Farq = missing.",
    ideaEn: "Idea. Sum of 0..n is n*(n+1)/2. Subtract the array sum. Difference is missing.",
    ideaHi: "आइडिया। 0..n का सम = n*(n+1)/2। ऐरे सम घटाओ। फ़र्क = मिसिंग।",
    ideaExtra: { stats: { formula: "n*(n+1)/2" }, codeLine: "long long sum = n*1LL*(n+1)/2;" },
    trickBoard: "XOR alternative",
    trickSay: "XOR bhi: saare indexes aur values xor. Pairs cancel, missing bachta.",
    trickEn: "XOR also works: xor all indexes and values. Pairs cancel, missing remains.",
    trickHi: "XOR भी: सारे इंडेक्स और वैल्यूज़। पेयर्स कैनसल, मिसिंग बचता।",
    trickExtra: { codeLine: "int x=n; for(int i=0;i<n;i++) x^=i^nums[i];" },
    dry: [
      { board: "Expect 6", say: "n=3. Expected sum 0+1+2+3=6.", sayEn: "n=3. Expected sum 0+1+2+3=6.", sayHi: "n=3। अपेक्षित सम 0+1+2+3=6।", stats: { expected: 6 }, gesture: "write" },
      { board: "Actual 4", say: "Array sum 3+0+1=4. Missing = 6-4 = 2.", sayEn: "Array sum 3+0+1=4. Missing = 6-4 = 2.", sayHi: "ऐरे सम 3+0+1=4। मिसिंग = 6-4 = 2।", hi: [0, 1, 2], stats: { actual: 4, missing: 2 }, codeLine: "return (int)(sum - actual);", gesture: "celebrate" },
      { board: "XOR check", say: "XOR path bhi 2 deta hai. Same answer, O(1) space.", sayEn: "XOR path also gives 2. Same answer, O(1) space.", sayHi: "XOR रास्ता भी 2 देता है। वही जवाब, O(1) स्पेस।", stats: { xor: 2 }, gesture: "celebrate" },
    ],
    wrapBoard: "Missing = 2",
    wrapSay: "Sum ya XOR — dono interview-ready. Ab tum likho.",
    wrapEn: "Sum or XOR — both interview-ready. Now you write it.",
    wrapHi: "सम या XOR — दोनों इंटरव्यू-रेडी। अब तुम लिखो।",
    wrapExtra: { stats: { answer: 2, time: "O(n)" } },
  }),

  recipeShow({
    id: "single-number-show",
    title: "Single Number — XOR Walk",
    subtitle: "Pairs cancel to zero; the lonely value remains.",
    kind: "array-scan",
    practiceIds: ["single-number"],
    cells: [4, 1, 2, 1, 2],
    hookBoard: "Single Number",
    hookSay: "Suno. Har number do baar, ek akela. Akela kaun?",
    hookEn: "Listen. Every number twice, one alone. Which is alone?",
    hookHi: "सुनो। हर नंबर दो बार, एक अकेला। अकेला कौन?",
    hookStats: { ask: "the lonely one" },
    contractBoard: "O(1) space",
    contractSay: "O(n) time, O(1) space chahiye. Hash allowed nahi ideally.",
    contractEn: "Need O(n) time, O(1) space. Ideally no hash map.",
    contractHi: "O(n) टाइम, O(1) स्पेस चाहिए। आइडियली हैश नहीं।",
    contractExtra: { stats: { constraint: "O(1) space" } },
    wrongBoard: "Hash count",
    wrongSay: "Map se count karo. Chalega. Par space O(n). XOR better.",
    wrongEn: "Count with a map. Works. But space O(n). XOR is better.",
    wrongHi: "मैप से काउंट। चलेगा। पर स्पेस O(n)। XOR बेहतर।",
    wrongExtra: { stats: { avoid: "hash O(n)" } },
    ideaBoard: "a^a = 0",
    ideaSay: "Idea. XOR: a^a=0, a^0=a. Saare XOR karo — pairs gaye, single bacha.",
    ideaEn: "Idea. XOR: a^a=0, a^0=a. XOR everything — pairs vanish, single remains.",
    ideaHi: "आइडिया। XOR: a^a=0, a^0=a। सब XOR — पेयर्स गए, सिंगल बचा।",
    ideaExtra: { codeLine: "int x = 0; for (int v : nums) x ^= v;" },
    trickBoard: "Order free",
    trickSay: "XOR commutative hai. Order matter nahi. Seedha fold.",
    trickEn: "XOR is commutative. Order does not matter. Just fold.",
    trickHi: "XOR कम्यूटेटिव है। ऑर्डर मायने नहीं। सीधा फोल्ड।",
    trickExtra: { stats: { property: "commutative" } },
    dry: [
      { board: "Start x=0", say: "x=0. 0^4=4. Ab x=4.", sayEn: "x=0. 0^4=4. Now x=4.", sayHi: "x=0। 0^4=4। अब x=4।", hi: [0], pointers: { i: 0 }, stats: { x: 4 } },
      { board: "Pairs cancel", say: "4^1^2^1^2. Dono 1 cancel, dono 2 cancel. x=4.", sayEn: "4^1^2^1^2. Both 1s cancel, both 2s cancel. x=4.", sayHi: "4^1^2^1^2। दोनों 1 कैनसल, दोनों 2 कैनसल। x=4।", hi: [0, 1, 2, 3, 4], stats: { x: 4 }, codeLine: "return x;", gesture: "celebrate" },
      { board: "Answer 4", say: "Single number 4. Bit magic clean.", sayEn: "Single number is 4. Clean bit magic.", sayHi: "सिंगल नंबर 4। बिट मैजिक क्लीन।", hi: [0], stats: { answer: 4 }, gesture: "celebrate" },
    ],
    wrapBoard: "Answer 4",
    wrapSay: "XOR fold. O(n)/O(1). Ab code likho.",
    wrapEn: "XOR fold. O(n)/O(1). Now write the code.",
    wrapHi: "XOR फोल्ड। O(n)/O(1)। अब कोड लिखो।",
    wrapExtra: { stats: { answer: 4, time: "O(n)" } },
  }),

  recipeShow({
    id: "majority-show",
    title: "Majority Element — Boyer-Moore",
    subtitle: "Candidate + count; the majority always survives.",
    kind: "array-scan",
    practiceIds: ["majority-element"],
    cells: [2, 2, 1, 1, 1, 2, 2],
    hookBoard: "Majority Element",
    hookSay: "Suno. Jo element n/2 se zyada baar aaye — majority. Find it.",
    hookEn: "Listen. The element appearing more than n/2 times — majority. Find it.",
    hookHi: "सुनो। जो एलिमेंट n/2 से ज़्यादा बार आए — मेजॉरिटी। ढूँढो।",
    hookStats: { n: 7, threshold: ">3" },
    contractBoard: "Majority guaranteed",
    contractSay: "Classic version mein majority hamesha exist karta. Return woh value.",
    contractEn: "In the classic version majority always exists. Return that value.",
    contractHi: "क्लासिक वर्जन में मेजॉरिटी हमेशा मौजूद। वही वैल्यू रिटर्न।",
    contractExtra: { stats: { return: "the majority value" } },
    wrongBoard: "Hash counts",
    wrongSay: "Map se count. O(n) space. Boyer-Moore O(1) space flex.",
    wrongEn: "Count with a map. O(n) space. Boyer-Moore flexes O(1) space.",
    wrongHi: "मैप से काउंट। O(n) स्पेस। बॉयर-मूर O(1) स्पेस फ्लेक्स।",
    wrongExtra: { stats: { avoid: "hash" } },
    ideaBoard: "Candidate + count",
    ideaSay: "Idea. Ek candidate rakho, count. Same → count++. Diff → count--.",
    ideaEn: "Idea. Keep a candidate and count. Same → count++. Diff → count--.",
    ideaHi: "आइडिया। एक कैंडिडेट और काउंट। सेम → count++। डिफ → count--।",
    ideaExtra: { codeLine: "int cand = 0, cnt = 0;" },
    trickBoard: "Reset at zero",
    trickSay: "Jab count 0, naya candidate lo. Majority cancel nahi hota completely.",
    trickEn: "When count hits 0, take a new candidate. Majority never fully cancels.",
    trickHi: "जब काउंट 0, नया कैंडिडेट। मेजॉरिटी पूरी तरह कैनसल नहीं होता।",
    trickExtra: { codeLine: "if (cnt == 0) cand = x;" },
    dry: [
      { board: "Start 2", say: "First 2. cand=2, cnt=1. Next 2 → cnt=2.", sayEn: "First 2. cand=2, cnt=1. Next 2 → cnt=2.", sayHi: "पहला 2। cand=2, cnt=1। अगला 2 → cnt=2।", hi: [0, 1], pointers: { i: 1 }, stats: { cand: 2, cnt: 2 } },
      { board: "Ones chip", say: "Teen 1 aate — cnt gir ke 0, phir cand=1 thoda, phir 2 wapas.", sayEn: "Three 1s arrive — cnt drops toward 0, brief cand=1, then 2 returns.", sayHi: "तीन 1 आते — cnt गिरता, थोड़ा cand=1, फिर 2 वापस।", hi: [2, 3, 4], pointers: { i: 4 }, stats: { note: "cancelling" } },
      { board: "Survivor 2", say: "Last do 2. cand=2 jeet-ta. Majority 2.", sayEn: "Last two 2s. cand=2 wins. Majority is 2.", sayHi: "आखिरी दो 2। cand=2 जीतता। मेजॉरिटी 2।", hi: [5, 6], pointers: { i: 6 }, stats: { cand: 2, answer: 2 }, codeLine: "return cand;", gesture: "celebrate" },
    ],
    wrapBoard: "Answer 2",
    wrapSay: "Boyer-Moore yaad rakhna. Ek pass, O(1) space. Ab likho.",
    wrapEn: "Remember Boyer-Moore. One pass, O(1) space. Now write it.",
    wrapHi: "बॉयर-मूर याद रखना। एक पास, O(1) स्पेस। अब लिखो।",
    wrapExtra: { stats: { answer: 2, time: "O(n)" } },
  }),

  recipeShow({
    id: "merge-sorted-show",
    title: "Merge Sorted Array — Fill from Back",
    subtitle: "Three pointers; write the larger value at the end.",
    kind: "two-pointers",
    practiceIds: ["merge-sorted-array"],
    cells: [1, 2, 3, 0, 0, 0],
    hookBoard: "Merge Sorted Array",
    hookSay: "Suno. nums1 mein m values + trailing zeros. nums2 ko merge in-place.",
    hookEn: "Listen. nums1 has m values plus trailing zeros. Merge nums2 in-place.",
    hookHi: "सुनो। nums1 में m वैल्यूज़ + ट्रेलिंग ज़ीरो। nums2 को इन-प्लेस मर्ज।",
    hookStats: { m: 3, n: 3, nums2: "2 5 6" },
    contractBoard: "nums1 becomes sorted",
    contractSay: "Result nums1 mein: [1,2,2,3,5,6]. Extra array mat banao ideally.",
    contractEn: "Result in nums1: [1,2,2,3,5,6]. Ideally no extra array.",
    contractHi: "रिजल्ट nums1 में: [1,2,2,3,5,6]। आइडियली एक्स्ट्रा ऐरे नहीं।",
    contractExtra: { stats: { goal: "[1,2,2,3,5,6]" } },
    wrongBoard: "Merge from front",
    wrongSay: "Aage se likhogе to overwrite. Isliye peeche se bharao.",
    wrongEn: "Writing from the front overwrites. So fill from the back.",
    wrongHi: "आगे से लिखोगे तो ओवरराइट। इसलिए पीछे से भरो।",
    wrongExtra: { stats: { avoid: "front write" } },
    ideaBoard: "i, j, k from ends",
    ideaSay: "i = m-1, j = n-1, k = m+n-1. Bada value k pe likho.",
    ideaEn: "i = m-1, j = n-1, k = m+n-1. Write the larger value at k.",
    ideaHi: "i = m-1, j = n-1, k = m+n-1। बड़ा वैल्यू k पर लिखो।",
    ideaExtra: { pointers: { i: 2, j: 2, k: 5 }, codeLine: "int i=m-1,j=n-1,k=m+n-1;" },
    trickBoard: "Compare tails",
    trickSay: "nums1[i] aur nums2[j] mein se bada uthao, k--, pointer--.",
    trickEn: "Take the larger of nums1[i] and nums2[j], write at k--, move that pointer.",
    trickHi: "nums1[i] और nums2[j] में से बड़ा उठाओ, k--, पॉइंटर--।",
    trickExtra: { codeLine: "if (nums1[i] > nums2[j]) nums1[k--]=nums1[i--];" },
    dry: [
      { board: "6 then 5", say: "3 vs 6 → likho 6. Phir 3 vs 5 → likho 5. nums1: [1,2,3,0,5,6].", sayEn: "3 vs 6 → write 6. Then 3 vs 5 → write 5. nums1: [1,2,3,0,5,6].", sayHi: "3 vs 6 → 6 लिखो। फिर 3 vs 5 → 5। nums1: [1,2,3,0,5,6]।", cells: [1, 2, 3, 0, 5, 6], hi: [4, 5], pointers: { i: 2, j: 0, k: 3 }, stats: { wrote: "6,5" }, gesture: "write" },
      { board: "2 then rest", say: "3 vs 2 → likho 3. Phir nums2 ka 2. Baaki 1,2 pehle se.", sayEn: "3 vs 2 → write 3. Then nums2's 2. Rest 1,2 already placed.", sayHi: "3 vs 2 → 3 लिखो। फिर nums2 का 2। बाकी 1,2 पहले से।", cells: [1, 2, 2, 3, 5, 6], hi: [0, 1, 2, 3, 4, 5], stats: { answer: "[1,2,2,3,5,6]" }, gesture: "celebrate" },
      { board: "Merged", say: "Done. Back-fill ne overwrite bachaya.", sayEn: "Done. Back-fill avoided overwrite.", sayHi: "डन। बैक-फिल ने ओवरराइट बचाया।", cells: [1, 2, 2, 3, 5, 6], stats: { status: "merged" }, gesture: "celebrate" },
    ],
    wrapBoard: "Merged",
    wrapSay: "Teen pointers, peeche se. O(m+n). Ab likho.",
    wrapEn: "Three pointers, from the back. O(m+n). Now write it.",
    wrapHi: "तीन पॉइंटर्स, पीछे से। O(m+n)। अब लिखो।",
    wrapExtra: { cells: [1, 2, 2, 3, 5, 6], stats: { time: "O(m+n)" } },
  }),

  recipeShow({
    id: "sort-colors-show",
    title: "Sort Colors — Dutch National Flag",
    subtitle: "lo / mid / hi one-pass partition of 0,1,2.",
    kind: "two-pointers",
    practiceIds: ["sort-colors"],
    cells: [2, 0, 2, 1, 1, 0],
    hookBoard: "Sort Colors",
    hookSay: "Suno. Array mein sirf 0,1,2. In-place sort. Dutch flag.",
    hookEn: "Listen. Array of only 0,1,2. Sort in-place. Dutch flag.",
    hookHi: "सुनो। ऐरे में सिर्फ 0,1,2। इन-प्लेस सॉर्ट। डच फ्लैग।",
    hookStats: { ask: "0s then 1s then 2s" },
    contractBoard: "One pass preferred",
    contractSay: "Counting sort bhi chalega. Interview one-pass three pointers chahta.",
    contractEn: "Counting sort also works. Interviews prefer one-pass three pointers.",
    contractHi: "काउंटिंग सॉर्ट भी चलेगा। इंटरव्यू वन-पास तीन पॉइंटर्स चाहता।",
    contractExtra: { stats: { goal: "[0,0,1,1,2,2]" } },
    wrongBoard: "Full sort",
    wrongSay: "sort() call? Too generic. Pattern dikhana hai.",
    wrongEn: "Just call sort()? Too generic. Show the pattern.",
    wrongHi: "sort() कॉल? बहुत जेनेरिक। पैटर्न दिखाना है।",
    wrongExtra: { stats: { avoid: "std::sort" } },
    ideaBoard: "lo mid hi",
    ideaSay: "lo=0, mid=0, hi=n-1. mid pe decide: 0/1/2.",
    ideaEn: "lo=0, mid=0, hi=n-1. Decide at mid: 0/1/2.",
    ideaHi: "lo=0, mid=0, hi=n-1। mid पर फ़ैसला: 0/1/2।",
    ideaExtra: { pointers: { lo: 0, mid: 0, hi: 5 }, codeLine: "int lo=0, mid=0, hi=n-1;" },
    trickBoard: "2: swap hi, don't mid++",
    trickSay: "0 → swap lo++, mid++. 1 → mid++. 2 → swap hi--, mid mat badhao.",
    trickEn: "0 → swap lo++, mid++. 1 → mid++. 2 → swap hi--, do not mid++.",
    trickHi: "0 → स्वैप lo++, mid++। 1 → mid++। 2 → स्वैप hi--, mid मत बढ़ाओ।",
    trickExtra: { codeLine: "else { swap(nums[mid], nums[hi--]); }" },
    dry: [
      { board: "First 2", say: "mid pe 2. Swap with hi. Array [0,0,2,1,1,2]. hi--. Recheck mid.", sayEn: "mid sees 2. Swap with hi. Array [0,0,2,1,1,2]. hi--. Recheck mid.", sayHi: "mid पर 2। hi से स्वैप। [0,0,2,1,1,2]। hi--। mid दोबारा चेक।", cells: [0, 0, 2, 1, 1, 2], pointers: { lo: 0, mid: 0, hi: 4 }, hi: [0, 5], gesture: "write" },
      { board: "Zeros left", say: "0s lo ki taraf jaate, 1s mid cross, 2s right pile.", sayEn: "0s move toward lo, 1s pass mid, 2s pile on the right.", sayHi: "0s लो की तरफ़, 1s मिड पार, 2s दाईं तरफ।", cells: [0, 0, 1, 1, 2, 2], hi: [0, 1], pointers: { lo: 2, mid: 4, hi: 3 }, stats: { progress: "partitioning" } },
      { board: "Done", say: "mid > hi. Sorted [0,0,1,1,2,2].", sayEn: "mid > hi. Sorted [0,0,1,1,2,2].", sayHi: "mid > hi। सॉर्टेड [0,0,1,1,2,2]।", cells: [0, 0, 1, 1, 2, 2], hi: [0, 1, 2, 3, 4, 5], stats: { answer: "[0,0,1,1,2,2]" }, gesture: "celebrate" },
    ],
    wrapBoard: "Dutch flag done",
    wrapSay: "Ek pass partition. Yaad: 2 ke baad mid++ mat. Ab likho.",
    wrapEn: "One-pass partition. Remember: no mid++ after a 2. Now write it.",
    wrapHi: "एक पास पार्टीशन। याद: 2 के बाद mid++ मत। अब लिखो।",
    wrapExtra: { cells: [0, 0, 1, 1, 2, 2], stats: { time: "O(n)" } },
  }),

  recipeShow({
    id: "product-except-show",
    title: "Product Except Self — Prefix × Suffix",
    subtitle: "Left products into ans, then multiply running right.",
    kind: "array-scan",
    practiceIds: ["product-except-self"],
    cells: [1, 2, 3, 4],
    hookBoard: "Product Except Self",
    hookSay: "Suno. Har index pe baaki sabka product. Division forbidden.",
    hookEn: "Listen. At each index, product of everything else. No division.",
    hookHi: "सुनो। हर इंडेक्स पर बाकी सबका प्रॉडक्ट। डिवीजन मना।",
    hookStats: { ask: "except self products" },
    contractBoard: "O(n) time",
    contractSay: "Output [24,12,8,6]. Extra O(1) space besides output preferred.",
    contractEn: "Output [24,12,8,6]. Prefer O(1) extra space besides output.",
    contractHi: "आउटपुट [24,12,8,6]। आउटपुट के अलावा O(1) स्पेस प्रेफर।",
    contractExtra: { stats: { goal: "[24,12,8,6]" } },
    wrongBoard: "Divide by nums[i]",
    wrongSay: "Total product / nums[i]? Zero pe toot-ta. Division bhi banned.",
    wrongEn: "Total product / nums[i]? Breaks on zero. Division also banned.",
    wrongHi: "टोटल / nums[i]? ज़ीरो पर टूटता। डिवीजन भी बैन।",
    wrongExtra: { stats: { avoid: "division" } },
    ideaBoard: "left[i] * right[i]",
    ideaSay: "ans[i] = leftProduct * rightProduct. Do passes.",
    ideaEn: "ans[i] = leftProduct * rightProduct. Two passes.",
    ideaHi: "ans[i] = लेफ्टप्रॉडक्ट * राइटप्रॉडक्ट। दो पास।",
    ideaExtra: { codeLine: "vector<int> ans(n, 1);" },
    trickBoard: "Reuse ans for left",
    trickSay: "Pehle left products ans mein. Phir running right se multiply.",
    trickEn: "First put left products in ans. Then multiply by a running right.",
    trickHi: "पहले लेफ्ट प्रॉडक्ट्स ans में। फिर रनिंग राइट से मल्टीप्लाई।",
    trickExtra: { codeLine: "for (int i=n-1, R=1; i>=0; --i) { ans[i]*=R; R*=nums[i]; }" },
    dry: [
      { board: "Left pass", say: "Left: ans=[1,1,2,6]. Har pe left ka product.", sayEn: "Left: ans=[1,1,2,6]. Product of everything to the left.", sayHi: "लेफ्ट: ans=[1,1,2,6]। बाईं तरफ का प्रॉडक्ट।", cells: [1, 1, 2, 6], hi: [0, 1, 2, 3], stats: { pass: "left" }, gesture: "write" },
      { board: "Right pass", say: "Right se: *24,*12,*4,*1 → [24,12,8,6].", sayEn: "From the right: *24,*12,*4,*1 → [24,12,8,6].", sayHi: "दाईं से: *24,*12,*4,*1 → [24,12,8,6]।", cells: [24, 12, 8, 6], hi: [0, 1, 2, 3], stats: { answer: "[24,12,8,6]" }, gesture: "celebrate" },
      { board: "Check", say: "Index 0: 2*3*4=24. Index 2: 1*2*4=8. Correct.", sayEn: "Index 0: 2*3*4=24. Index 2: 1*2*4=8. Correct.", sayHi: "इंडेक्स 0: 2*3*4=24। इंडेक्स 2: 1*2*4=8। सही।", cells: [24, 12, 8, 6], stats: { verified: "yes" }, gesture: "celebrate" },
    ],
    wrapBoard: "No division",
    wrapSay: "Prefix × suffix. Two passes. Ab tum likho.",
    wrapEn: "Prefix × suffix. Two passes. Now you write it.",
    wrapHi: "प्रीफिक्स × सफिक्स। दो पास। अब तुम लिखो।",
    wrapExtra: { cells: [24, 12, 8, 6], stats: { time: "O(n)" } },
  }),
];

WAVE3.push(
  recipeShow({
    id: "first-unique-show",
    title: "First Unique Character — Count then Scan",
    subtitle: "Frequency pass, then first index with count 1.",
    kind: "hash-map",
    practiceIds: ["first-unique-char"],
    cells: ["l", "e", "e", "t", "c", "o", "d", "e"],
    hookBoard: "First Unique Char",
    hookSay: "Suno. String mein pehla character jiska count exactly 1 ho.",
    hookEn: "Listen. First character in the string whose count is exactly 1.",
    hookHi: "सुनो। स्ट्रिंग में पहला कैरेक्टर जिसका काउंट ठीक 1 हो।",
    hookStats: { ask: "first unique index" },
    contractBoard: "Return index or -1",
    contractSay: "Index return. Agar koi unique nahi, -1. leetcode → 0 ('l').",
    contractEn: "Return the index. If none unique, -1. leetcode → 0 ('l').",
    contractHi: "इंडेक्स रिटर्न। अगर कोई यूनिक नहीं, -1। leetcode → 0 ('l')।",
    contractExtra: { stats: { example: "leetcode → 0" } },
    wrongBoard: "Nested scan",
    wrongSay: "Har char ke liye poori string count? O(n²). Do pass better.",
    wrongEn: "Count whole string per char? O(n²). Two passes are better.",
    wrongHi: "हर कैरेक्टर के लिए पूरी स्ट्रिंग? O(n²)। दो पास बेहतर।",
    wrongExtra: { stats: { avoid: "O(n²)" } },
    ideaBoard: "freq[26]",
    ideaSay: "Pehle freq array bharo. Phir left-to-right pehla freq==1.",
    ideaEn: "Fill a freq array first. Then left-to-right first freq==1.",
    ideaHi: "पहले फ़्रीक ऐरे भरो। फिर लेफ्ट-टू-राइट पहला freq==1।",
    ideaExtra: { map: {}, codeLine: "int freq[26] = {};" },
    trickBoard: "Second pass",
    trickSay: "Second pass order preserve karta — pehla unique milte hi return.",
    trickEn: "Second pass preserves order — return as soon as first unique is found.",
    trickHi: "दूसरा पास ऑर्डर बचाता — पहला यूनिक मिलते ही रिटर्न।",
    trickExtra: { codeLine: "if (freq[s[i]-'a']==1) return i;" },
    dry: [
      { board: "Count pass", say: "l:1 e:3 t:1 c:1 o:1 d:1. Map ready.", sayEn: "l:1 e:3 t:1 c:1 o:1 d:1. Map ready.", sayHi: "l:1 e:3 t:1 c:1 o:1 d:1। मैप रेडी।", map: { l: 1, e: 3, t: 1, c: 1, o: 1, d: 1 }, stats: { pass: "count" }, gesture: "write" },
      { board: "First unique l", say: "Index 0 'l' freq 1. Hit! Return 0.", sayEn: "Index 0 'l' has freq 1. Hit! Return 0.", sayHi: "इंडेक्स 0 'l' फ़्रीक 1। हिट! रिटर्न 0।", hi: [0], pointers: { i: 0 }, stats: { answer: 0 }, codeLine: "return 0;", gesture: "celebrate" },
      { board: "Contrast", say: "loveleetcode mein pehla unique 'v' at 2. Pattern same.", sayEn: "In loveleetcode first unique is 'v' at 2. Same pattern.", sayHi: "loveleetcode में पहला यूनिक 'v' at 2। पैटर्न वही।", stats: { note: "other example → 2" }, gesture: "celebrate" },
    ],
    wrapBoard: "Index 0",
    wrapSay: "Count, then scan. O(n). Ab likho.",
    wrapEn: "Count, then scan. O(n). Now write it.",
    wrapHi: "काउंट, फिर स्कैन। O(n)। अब लिखो।",
    wrapExtra: { stats: { answer: 0, time: "O(n)" } },
  }),

  recipeShow({
    id: "isomorphic-show",
    title: "Isomorphic Strings — Bijection Map",
    subtitle: "Map s→t and ensure no two letters claim the same t.",
    kind: "hash-map",
    practiceIds: ["isomorphic-strings"],
    cells: ["e", "g", "g"],
    hookBoard: "Isomorphic Strings",
    hookSay: "Suno. s aur t isomorphic? Har char ka 1:1 mapping.",
    hookEn: "Listen. Are s and t isomorphic? A 1:1 mapping of characters.",
    hookHi: "सुनो। s और t आइसोमॉर्फिक? हर कैरेक्टर का 1:1 मैपिंग।",
    hookStats: { s: "egg", t: "add", ask: "isomorphic?" },
    contractBoard: "Same length + bijection",
    contractSay: "Length equal. Mapping consistent dono taraf. egg→add true.",
    contractEn: "Equal length. Mapping consistent both ways. egg→add is true.",
    contractHi: "लेंथ बराबर। मैपिंग दोनों तरफ़Consistent। egg→add ट्रू।",
    contractExtra: { stats: { example: "egg → add = true" } },
    wrongBoard: "One-way map only",
    wrongSay: "Sirf s→t map? foo→bar fail miss ho sakta. t claimed check chahiye.",
    wrongEn: "Only s→t map? You can miss foo→bar failure. Check t is not double-claimed.",
    wrongHi: "सिर्फ s→t मैप? foo→bar फेल मिस हो सकता। t क्लेम्ड चेक चाहिए।",
    wrongExtra: { stats: { avoid: "one-way only" } },
    ideaBoard: "Two maps",
    ideaSay: "mpST aur mpTS. Ya map + set of used t chars.",
    ideaEn: "mpST and mpTS. Or a map plus a set of used t chars.",
    ideaHi: "mpST और mpTS। या मैप + यूज़्ड t कैरेक्टर्स का सेट।",
    ideaExtra: { map: {}, codeLine: "unordered_map<char,char> st, ts;" },
    trickBoard: "Conflict checks",
    trickSay: "Agar s pehle se mapped aur alag t? False. t pehle kisi aur s se? False.",
    trickEn: "If s already mapped to a different t? False. If t already taken by another s? False.",
    trickHi: "अगर s पहले से मैप्ड और अलग t? फॉल्स। t पहले किसी और s से? फॉल्स।",
    trickExtra: { codeLine: "if (st.count(a) && st[a]!=b) return false;" },
    dry: [
      { board: "e → a", say: "e→a map. g→d map. Second g bhi d. Consistent. True.", sayEn: "Map e→a. Map g→d. Second g also d. Consistent. True.", sayHi: "e→a मैप। g→d मैप। दूसरा g भी d।Consistent। ट्रू।", cells: ["e", "g", "g"], map: { e: "a", g: "d" }, hi: [0, 1, 2], stats: { answer: "true" }, gesture: "celebrate" },
      { board: "foo / bar fail", say: "Contrast: foo→bar. o pehle r, phir a chahiye — conflict. False.", sayEn: "Contrast: foo→bar. o first maps to r, then wants a — conflict. False.", sayHi: "कंट्रास्ट: foo→bar। o पहले r, फिर a — कॉन्फ्लिक्ट। फॉल्स।", cells: ["f", "o", "o"], map: { f: "b", o: "r" }, stats: { conflict: "o→a vs o→r" }, gesture: "think" },
      { board: "paper / title", say: "paper→title bhi true. Pattern solid.", sayEn: "paper→title is also true. Pattern is solid.", sayHi: "paper→title भी ट्रू। पैटर्न सॉलिड।", stats: { note: "another true case" }, gesture: "celebrate" },
    ],
    wrapBoard: "Bijection",
    wrapSay: "Do maps, conflict checks. Ab tum likho.",
    wrapEn: "Two maps, conflict checks. Now you write it.",
    wrapHi: "दो मैप्स, कॉन्फ्लिक्ट चेक्स। अब तुम लिखो।",
    wrapExtra: { stats: { answer: "true", time: "O(n)" } },
  }),

  recipeShow({
    id: "happy-number-show",
    title: "Happy Number — Digit Square Cycle",
    subtitle: "Sum of digit squares; detect cycles with a set.",
    kind: "hash-map",
    practiceIds: ["happy-number"],
    cells: [19],
    hookBoard: "Happy Number",
    hookSay: "Suno. Digit ke squares ka sum bar-bar. 1 pe pahunche to happy.",
    hookEn: "Listen. Keep summing digit squares. Reach 1 → happy.",
    hookHi: "सुनो। डिजिट स्क्वेयर्स का सम बार-बार। 1 पर पहुँचे तो हैप्पी।",
    hookStats: { n: 19, ask: "happy?" },
    contractBoard: "true / false",
    contractSay: "Happy → true. Cycle mein fasoge (jaise 2) → false.",
    contractEn: "Happy → true. Stuck in a cycle (like 2) → false.",
    contractHi: "हैप्पी → ट्रू। साइकल में फँसे (जैसे 2) → फॉल्स।",
    contractExtra: { stats: { return: "bool" } },
    wrongBoard: "Infinite loop risk",
    wrongSay: "Bina seen set ke loop forever. Cycle detect zaroori.",
    wrongEn: "Without a seen set you loop forever. Cycle detect is required.",
    wrongHi: "सीन सेट बिना हमेशा लूप। साइकल डिटेक्ट ज़रूरी।",
    wrongExtra: { stats: { avoid: "no cycle check" } },
    ideaBoard: "next = Σ digit²",
    ideaSay: "Helper: next number = sum of digit squares. Set mein seen rakho.",
    ideaEn: "Helper: next = sum of digit squares. Keep seen in a set.",
    ideaHi: "हेल्पर: नेक्स्ट = डिजिट स्क्वेयर्स का सम। सेट में सीन रखो।",
    ideaExtra: { map: {}, codeLine: "unordered_set<int> seen;" },
    trickBoard: "Repeat → false",
    trickSay: "Agar number pehle aa chuka, cycle. Return false. 1 → true.",
    trickEn: "If a number repeats, cycle. Return false. Hit 1 → true.",
    trickHi: "अगर नंबर दोहराया, साइकल। फॉल्स। 1 → ट्रू।",
    trickExtra: { codeLine: "if (!seen.insert(n).second) return false;" },
    dry: [
      { board: "19 → 82", say: "1²+9²=1+81=82. Seen: {19}.", sayEn: "1²+9²=1+81=82. Seen: {19}.", sayHi: "1²+9²=1+81=82। सीन: {19}।", cells: [19, 82], map: { "19": 1 }, stats: { next: 82 } },
      { board: "82 → 68 → 100", say: "82→68→100. Squares chain clean.", sayEn: "82→68→100. Clean square chain.", sayHi: "82→68→100। स्क्वेयर चेन क्लीन।", cells: [82, 68, 100], map: { "19": 1, "82": 1, "68": 1 }, stats: { next: 100 }, gesture: "write" },
      { board: "100 → 1", say: "1+0+0=1. Happy! Return true.", sayEn: "1+0+0=1. Happy! Return true.", sayHi: "1+0+0=1। हैप्पी! ट्रू रिटर्न।", cells: [100, 1], stats: { answer: "true" }, codeLine: "return true;", gesture: "celebrate" },
    ],
    wrapBoard: "19 is happy",
    wrapSay: "Digit square + cycle set. Floyd bhi option. Ab likho.",
    wrapEn: "Digit square + cycle set. Floyd is an option too. Now write it.",
    wrapHi: "डिजिट स्क्वेयर + साइकल सेट। फ्लॉयड भी ऑप्शन। अब लिखो।",
    wrapExtra: { stats: { answer: "true", time: "O(log n)" } },
  }),

  recipeShow({
    id: "longest-consecutive-show",
    title: "Longest Consecutive — Set Streaks",
    subtitle: "Only start a run when x-1 is missing; count upward.",
    kind: "hash-map",
    practiceIds: ["longest-consecutive"],
    cells: [100, 4, 200, 1, 3, 2],
    hookBoard: "Longest Consecutive",
    hookSay: "Suno. Numbers ki sabse lambi consecutive streak — sort ke bina O(n).",
    hookEn: "Listen. Longest consecutive streak of numbers — O(n) without sorting.",
    hookHi: "सुनो। नंबर्स की सबसे लंबीConsecutive स्ट्रीक — सॉर्ट बिना O(n)।",
    hookStats: { ask: "longest run length" },
    contractBoard: "Length only",
    contractSay: "Sequence return nahi — length. Yahan 1,2,3,4 → 4.",
    contractEn: "Return length, not the sequence. Here 1,2,3,4 → 4.",
    contractHi: "सीक्वेंस नहीं — लेंथ। यहाँ 1,2,3,4 → 4।",
    contractExtra: { stats: { expect: 4 } },
    wrongBoard: "Sort first",
    wrongSay: "Sort O(n log n). Set + smart starts O(n).",
    wrongEn: "Sorting is O(n log n). Set + smart starts is O(n).",
    wrongHi: "सॉर्ट O(n log n)। सेट + स्मार्ट स्टार्ट O(n)।",
    wrongExtra: { stats: { avoid: "sort" } },
    ideaBoard: "unordered_set",
    ideaSay: "Saare nums set mein. Sirf tab streak shuru jab x-1 set mein na ho.",
    ideaEn: "Put all nums in a set. Only start a streak when x-1 is absent.",
    ideaHi: "सारे नंबर्स सेट में। सिर्फ तब स्ट्रीक जब x-1 सेट में न हो।",
    ideaExtra: { map: { "100": 1, "4": 1, "200": 1, "1": 1, "3": 1, "2": 1 }, codeLine: "unordered_set<int> s(nums.begin(), nums.end());" },
    trickBoard: "Count upward",
    trickSay: "Start se x+1, x+2… jab tak set mein. Length update.",
    trickEn: "From start count x+1, x+2… while in set. Update length.",
    trickHi: "स्टार्ट से x+1, x+2… जब तक सेट में। लेंथ अपडेट।",
    trickExtra: { codeLine: "while (s.count(x + len)) ++len;" },
    dry: [
      { board: "Skip middles", say: "4 skip — kyunki 3 exist. 2,3 bhi skip. Sirf starts matter.", sayEn: "Skip 4 — because 3 exists. Skip 2,3 too. Only starts matter.", sayHi: "4 स्किप — क्योंकि 3 है। 2,3 भी स्किप। सिर्फ स्टार्ट्स।", hi: [1], stats: { skip: "not a start" } },
      { board: "Start at 1", say: "1 start. 2,3,4 set mein. Streak length 4. Best!", sayEn: "1 is a start. 2,3,4 in set. Streak length 4. Best!", sayHi: "1 स्टार्ट। 2,3,4 सेट में। स्ट्रीक 4। बेस्ट!", hi: [3, 5, 4, 1], stats: { streak: 4, best: 4 }, gesture: "celebrate" },
      { board: "Loners", say: "100 aur 200 length 1. Best rehta 4.", sayEn: "100 and 200 are length 1. Best stays 4.", sayHi: "100 और 200 लेंथ 1। बेस्ट 4 रहता।", hi: [0, 2], stats: { answer: 4 }, gesture: "celebrate" },
    ],
    wrapBoard: "Answer 4",
    wrapSay: "Set + start-only rule. O(n). Ab likho.",
    wrapEn: "Set + start-only rule. O(n). Now write it.",
    wrapHi: "सेट + सिर्फ-स्टार्ट रूल। O(n)। अब लिखो।",
    wrapExtra: { stats: { answer: 4, time: "O(n)" } },
  }),

  recipeShow({
    id: "two-sum-ii-show",
    title: "Two Sum II — Sorted Two Pointers",
    subtitle: "L/R from ends; move by comparing sum to target.",
    kind: "two-pointers",
    practiceIds: ["two-sum-ii"],
    cells: [2, 7, 11, 15],
    hookBoard: "Two Sum II",
    hookSay: "Suno. Sorted array. Target sum. Indexes 1-based return.",
    hookEn: "Listen. Sorted array. Target sum. Return 1-based indexes.",
    hookHi: "सुनो। सॉर्टेड ऐरे। टारगेट सम। इंडेक्स 1-बेस्ड रिटर्न।",
    hookStats: { target: 9, ask: "1-based pair" },
    contractBoard: "Exactly one solution",
    contractSay: "Guarantee ek solution. Yahan 2+7=9 → indexes 1 aur 2.",
    contractEn: "Exactly one solution guaranteed. Here 2+7=9 → indexes 1 and 2.",
    contractHi: "एक सॉल्यूशन गारंटी। यहाँ 2+7=9 → इंडेक्स 1 और 2।",
    contractExtra: { stats: { return: "[1, 2]" }, hi: [0, 1] },
    wrongBoard: "Hash again",
    wrongSay: "Hash chalega, par sorted ka fayda lo — two pointers O(1) space.",
    wrongEn: "Hash works, but use sorted — two pointers O(1) space.",
    wrongHi: "हैश चलेगा, पर सॉर्टेड का फ़ायदा लो — टू पॉइंटर्स O(1) स्पेस।",
    wrongExtra: { stats: { prefer: "two pointers" } },
    ideaBoard: "L=0, R=n-1",
    ideaSay: "Ends se start. Sum dekho. Chhota → L++. Bada → R--.",
    ideaEn: "Start at ends. Check sum. Too small → L++. Too big → R--.",
    ideaHi: "एंड्स से शुरू। सम देखो। छोटा → L++। बड़ा → R--।",
    ideaExtra: { pointers: { L: 0, R: 3 }, codeLine: "int L=0, R=n-1;" },
    trickBoard: "1-based return",
    trickSay: "Jab sum==target, return {L+1, R+1}. Zero-based mat bhoolna.",
    trickEn: "When sum==target, return {L+1, R+1}. Do not forget 1-based.",
    trickHi: "जब सम==टारगेट, return {L+1, R+1}। 1-बेस्ड मत भूलना।",
    trickExtra: { codeLine: "return {L+1, R+1};" },
    dry: [
      { board: "2+15 too big", say: "L=0,R=3: 2+15=17 > 9. R--.", sayEn: "L=0,R=3: 2+15=17 > 9. R--.", sayHi: "L=0,R=3: 2+15=17 > 9। R--।", hi: [0, 3], pointers: { L: 0, R: 3 }, stats: { sum: 17 } },
      { board: "2+11 still big", say: "2+11=13 > 9. R-- phir.", sayEn: "2+11=13 > 9. R-- again.", sayHi: "2+11=13 > 9। फिर R--।", hi: [0, 2], pointers: { L: 0, R: 2 }, stats: { sum: 13 } },
      { board: "2+7 hit", say: "2+7=9. Hit! Return [1,2].", sayEn: "2+7=9. Hit! Return [1,2].", sayHi: "2+7=9। हिट! रिटर्न [1,2]।", hi: [0, 1], pointers: { L: 0, R: 1 }, stats: { answer: "[1, 2]" }, codeLine: "return {1, 2};", gesture: "celebrate" },
    ],
    wrapBoard: "Indexes 1,2",
    wrapSay: "Sorted two pointers. O(n)/O(1). Ab likho.",
    wrapEn: "Sorted two pointers. O(n)/O(1). Now write it.",
    wrapHi: "सॉर्टेड टू पॉइंटर्स। O(n)/O(1)। अब लिखो।",
    wrapExtra: { stats: { answer: "[1,2]", time: "O(n)" } },
  }),
);
