import { recipeShow } from "./wave3-full.mjs";

export const WAVE3C = [
  recipeShow({
    id: "invert-tree-show",
    title: "Invert Binary Tree — Swap Kids",
    subtitle: "Swap left and right recursively (or via BFS).",
    kind: "array-scan",
    practiceIds: ["invert-binary-tree"],
    cells: [4, 2, 7, 1, 3, 6, 9],
    hookBoard: "Invert Binary Tree",
    hookSay: "Suno. Tree ka mirror banao — har node pe left/right swap.",
    hookEn: "Listen. Mirror the tree — swap left and right at every node.",
    hookHi: "सुनो। ट्री का मिरर बनाओ — हर नोड पर left/right स्वैप।",
    hookStats: { ask: "mirrored tree" },
    contractBoard: "Return root",
    contractSay: "Same root return. Structure mirror. 4 ke kids 2↔7.",
    contractEn: "Return the same root. Structure mirrored. Kids of 4: 2↔7.",
    contractHi: "वही रूट रिटर्न। स्ट्रक्चर मिरर। 4 के किड्स 2↔7।",
    contractExtra: { stats: { root: 4 } },
    wrongBoard: "Rebuild values",
    wrongSay: "Level-order values rearrange? Overkill. Pointer swap enough.",
    wrongEn: "Rearrange level-order values? Overkill. Pointer swaps are enough.",
    wrongHi: "लेवल-ऑर्डर वैल्यूज़ रीअरेंज? ओवरकिल। पॉइंटर स्वैप काफी।",
    wrongExtra: { stats: { avoid: "rebuild" } },
    ideaBoard: "Recurse swap",
    ideaSay: "Null base. Swap left/right. Invert dono subtrees.",
    ideaEn: "Null base case. Swap left/right. Invert both subtrees.",
    ideaHi: "Null बेस। left/right स्वैप। दोनों सबट्री इनवर्ट।",
    ideaExtra: { codeLine: "if (!root) return nullptr;" },
    trickBoard: "Order free",
    trickSay: "Pehle swap phir recurse, ya pehle recurse phir swap — dono OK.",
    trickEn: "Swap then recurse, or recurse then swap — both OK.",
    trickHi: "पहले स्वैप फिर रीकर्स, या उल्टा — दोनों ओके।",
    trickExtra: { codeLine: "swap(root->left, root->right);" },
    dry: [
      { board: "Root swap", say: "Root 4: left 2 aur right 7 swap. Ab 7 left, 2 right.", sayEn: "Root 4: swap left 2 and right 7. Now 7 left, 2 right.", sayHi: "रूट 4: लेफ्ट 2 और राइट 7 स्वैप। अब 7 लेफ्ट, 2 राइट।", cells: [4, 7, 2, 9, 6, 3, 1], hi: [1, 2], stats: { swapped: "2↔7" }, gesture: "write" },
      { board: "Subtrees", say: "Har subtree bhi mirror. 7 ke kids 9↔6, 2 ke 3↔1.", sayEn: "Each subtree mirrors too. Kids of 7: 9↔6, of 2: 3↔1.", sayHi: "हर सबट्री भी मिरर। 7 के 9↔6, 2 के 3↔1।", cells: [4, 7, 2, 9, 6, 3, 1], hi: [3, 4, 5, 6], stats: { depth: "recursive" } },
      { board: "Mirrored", say: "Poora tree invert. Return root.", sayEn: "Whole tree inverted. Return root.", sayHi: "पूरा ट्री इनवर्ट। रूट रिटर्न।", cells: [4, 7, 2, 9, 6, 3, 1], stats: { answer: "mirrored" }, codeLine: "return root;", gesture: "celebrate" },
    ],
    wrapBoard: "Mirror done",
    wrapSay: "Swap + recurse. BFS queue bhi chalega. Ab likho.",
    wrapEn: "Swap + recurse. BFS queue also works. Now write it.",
    wrapHi: "स्वैप + रीकर्स। BFS क्यू भी चलेगा। अब लिखो।",
    wrapExtra: { cells: [4, 7, 2, 9, 6, 3, 1], stats: { time: "O(n)" } },
  }),

  recipeShow({
    id: "max-depth-show",
    title: "Max Depth of Tree — Recurse Heights",
    subtitle: "depth = 1 + max(leftDepth, rightDepth).",
    kind: "array-scan",
    practiceIds: ["max-depth-tree"],
    cells: [3, 9, 20, "·", "·", 15, 7],
    hookBoard: "Max Depth",
    hookSay: "Suno. Root se deepest leaf tak kitne nodes — depth.",
    hookEn: "Listen. How many nodes from root to the deepest leaf — depth.",
    hookHi: "सुनो। रूट से सबसे गहरी लीफ तक कितने नोड्स — डेप्थ।",
    hookStats: { ask: "max depth" },
    contractBoard: "Integer depth",
    contractSay: "Empty tree 0. Single node 1. Is example mein 3.",
    contractEn: "Empty tree 0. Single node 1. In this example 3.",
    contractHi: "खाली ट्री 0। सिंगल नोड 1। इस उदाहरण में 3।",
    contractExtra: { stats: { expect: 3 } },
    wrongBoard: "Only count left",
    wrongSay: "Sirf ek side? Galat. Dono ki max leni hai.",
    wrongEn: "Only one side? Wrong. You need the max of both.",
    wrongHi: "सिर्फ एक साइड? गलत। दोनों की मैक्स लेनी है।",
    wrongExtra: { stats: { avoid: "one child only" } },
    ideaBoard: "1 + max(L,R)",
    ideaSay: "Null → 0. Else 1 + max(depth(left), depth(right)).",
    ideaEn: "Null → 0. Else 1 + max(depth(left), depth(right)).",
    ideaHi: "Null → 0। वरना 1 + max(depth(left), depth(right))।",
    ideaExtra: { codeLine: "if (!root) return 0;" },
    trickBoard: "Both sides",
    trickSay: "Left 9 leaf → depth 1 se. Right 20→15/7 → deeper.",
    trickEn: "Left 9 is a leaf contribution. Right 20→15/7 goes deeper.",
    trickHi: "लेफ्ट 9 लीफ। राइट 20→15/7 और गहरा।",
    trickExtra: { codeLine: "return 1 + max(maxDepth(L), maxDepth(R));" },
    dry: [
      { board: "Leaf depths", say: "9 → 1. 15→1. 7→1. Parents pe build.", sayEn: "9 → 1. 15→1. 7→1. Build at parents.", sayHi: "9 → 1। 15→1। 7→1। पेरेंट्स पर बिल्ड।", hi: [1, 5, 6], stats: { leaves: 1 } },
      { board: "Node 20", say: "20 pe 1+max(1,1)=2. Root pe 1+max(1,2)=3.", sayEn: "At 20: 1+max(1,1)=2. At root: 1+max(1,2)=3.", sayHi: "20 पर 1+max(1,1)=2। रूट पर 1+max(1,2)=3।", hi: [0, 2], stats: { depth20: 2, depthRoot: 3 }, gesture: "write" },
      { board: "Answer 3", say: "Max depth 3. Recursion clean.", sayEn: "Max depth 3. Clean recursion.", sayHi: "मैक्स डेप्थ 3। रीकर्शन क्लीन।", stats: { answer: 3 }, codeLine: "return 3;", gesture: "celebrate" },
    ],
    wrapBoard: "Depth 3",
    wrapSay: "Classic tree DP. Ab likho.",
    wrapEn: "Classic tree DP. Now write it.",
    wrapHi: "क्लासिक ट्री DP। अब लिखो।",
    wrapExtra: { stats: { answer: 3, time: "O(n)" } },
  }),

  recipeShow({
    id: "same-tree-show",
    title: "Same Tree — Structural Recursion",
    subtitle: "Both null OK; values match and both subtrees match.",
    kind: "array-scan",
    practiceIds: ["same-tree"],
    cells: [1, 2, 3],
    hookBoard: "Same Tree",
    hookSay: "Suno. Do trees identical hain — structure aur values?",
    hookEn: "Listen. Are two trees identical — structure and values?",
    hookHi: "सुनो। दो ट्रीज एक जैसे हैं — स्ट्रक्चर और वैल्यूज़?",
    hookStats: { ask: "identical?" },
    contractBoard: "true / false",
    contractSay: "Dono [1,2,3] → true. Structure alag → false.",
    contractEn: "Both [1,2,3] → true. Different structure → false.",
    contractHi: "दोनों [1,2,3] → ट्रू। स्ट्रक्चर अलग → फॉल्स।",
    contractExtra: { stats: { expect: "true" } },
    wrongBoard: "Serialize compare",
    wrongSay: "String bana ke compare? Extra work. Recursion direct.",
    wrongEn: "Serialize then compare? Extra work. Recurse directly.",
    wrongHi: "स्ट्रिंग बनाके कम्पेयर? एक्स्ट्रा वर्क। सीधा रीकर्स।",
    wrongExtra: { stats: { avoid: "serialize" } },
    ideaBoard: "Three checks",
    ideaSay: "Dono null → true. Ek null → false. Val equal + same(L) + same(R).",
    ideaEn: "Both null → true. One null → false. Vals equal + same(L) + same(R).",
    ideaHi: "दोनों null → ट्रू। एक null → फॉल्स। वैल्यूज़ + same(L) + same(R)।",
    ideaExtra: { codeLine: "if (!p || !q) return p == q;" },
    trickBoard: "Short-circuit",
    trickSay: "Val mismatch pe turant false. Warna dono subtrees.",
    trickEn: "On value mismatch return false immediately. Else both subtrees.",
    trickHi: "वैल्यू मिसमैच पर तुरंत फॉल्स। वरना दोनों सबट्री।",
    trickExtra: { codeLine: "return p->val==q->val && isSame(p->left,q->left) && ..." },
    dry: [
      { board: "Roots 1=1", say: "Roots dono 1. Match. Ab left check.", sayEn: "Both roots are 1. Match. Check left.", sayHi: "रूट्स दोनों 1। मैच। अब लेफ्ट चेक।", hi: [0], stats: { roots: "ok" } },
      { board: "Kids match", say: "Left 2=2, right 3=3. Saare nulls align. True.", sayEn: "Left 2=2, right 3=3. All nulls align. True.", sayHi: "लेफ्ट 2=2, राइट 3=3। सारे null अलाइन। ट्रू।", hi: [1, 2], stats: { answer: "true" }, gesture: "celebrate" },
      { board: "Counterexample", say: "Agar ek side null dusri value — false. Pattern clear.", sayEn: "If one side null and the other a value — false. Pattern clear.", sayHi: "अगर एक साइड null दूसरी वैल्यू — फॉल्स। पैटर्न क्लियर।", stats: { note: "structure matters" }, gesture: "celebrate" },
    ],
    wrapBoard: "Same = true",
    wrapSay: "Recursion checklist. Ab likho.",
    wrapEn: "Recursion checklist. Now write it.",
    wrapHi: "रीकर्शन चेकलिस्ट। अब लिखो।",
    wrapExtra: { stats: { answer: "true", time: "O(n)" } },
  }),

  recipeShow({
    id: "climb-stairs-show",
    title: "Climb Stairs — Fibonacci DP",
    subtitle: "ways(n) = ways(n-1) + ways(n-2).",
    kind: "kadane",
    practiceIds: ["climb-stairs"],
    cells: [1, 2, 3, 4, 5],
    hookBoard: "Climb Stairs",
    hookSay: "Suno. n stairs. Har baar 1 ya 2 steps. Kitne ways?",
    hookEn: "Listen. n stairs. Each move 1 or 2 steps. How many ways?",
    hookHi: "सुनो। n सीढ़ियाँ। हर बार 1 या 2 स्टेप्स। कितने तरीके?",
    hookStats: { n: 5, ask: "number of ways" },
    contractBoard: "Count ways",
    contractSay: "Order matter karta. n=3 → 3 ways. n=5 → 8.",
    contractEn: "Order matters. n=3 → 3 ways. n=5 → 8.",
    contractHi: "ऑर्डर मायने रखता। n=3 → 3 तरीके। n=5 → 8।",
    contractExtra: { stats: { "n=5": 8 } },
    wrongBoard: "Recurse raw",
    wrongSay: "Seedha recursion exponential. DP / rolling vars chahiye.",
    wrongEn: "Naive recursion is exponential. Need DP or rolling vars.",
    wrongHi: "सीधा रीकर्शन एक्सपोनेंशियल। DP / रोलिंग वर चाहिए।",
    wrongExtra: { stats: { avoid: "naive recursion" } },
    ideaBoard: "Fib relation",
    ideaSay: "Last step 1 tha → ways(n-1). Last 2 → ways(n-2). Add.",
    ideaEn: "Last step was 1 → ways(n-1). Last was 2 → ways(n-2). Add.",
    ideaHi: "लास्ट स्टेप 1 → ways(n-1)। लास्ट 2 → ways(n-2)। जोड़ो।",
    ideaExtra: { codeLine: "int a=1, b=1; // ways(1), ways(2) carefully" },
    trickBoard: "O(1) space",
    trickSay: "Sirf pichhle do numbers. Array ki zarurat nahi.",
    trickEn: "Only the previous two numbers. No array needed.",
    trickHi: "सिर्फ पिछले दो नंबर। ऐरे की ज़रूरत नहीं।",
    trickExtra: { codeLine: "for (int i=3;i<=n;i++) { int c=a+b; a=b; b=c; }" },
    dry: [
      { board: "Base", say: "ways(1)=1, ways(2)=2.", sayEn: "ways(1)=1, ways(2)=2.", sayHi: "ways(1)=1, ways(2)=2।", hi: [0, 1], stats: { w1: 1, w2: 2 } },
      { board: "Build up", say: "w3=3, w4=5, w5=8. Fibonacci dikh raha.", sayEn: "w3=3, w4=5, w5=8. Fibonacci appearing.", sayHi: "w3=3, w4=5, w5=8। फिबोनाची दिख रहा।", hi: [2, 3, 4], cells: [1, 2, 3, 5, 8], stats: { w5: 8 }, gesture: "write" },
      { board: "Answer 8", say: "n=5 → 8 ways. Done.", sayEn: "n=5 → 8 ways. Done.", sayHi: "n=5 → 8 तरीके। डन।", stats: { answer: 8 }, codeLine: "return b;", gesture: "celebrate" },
    ],
    wrapBoard: "Fib climbed",
    wrapSay: "DP intuition solid. Ab likho.",
    wrapEn: "DP intuition solid. Now write it.",
    wrapHi: "DP इंट्यूशन सॉलिड। अब लिखो।",
    wrapExtra: { stats: { answer: 8, time: "O(n)" } },
  }),

  recipeShow({
    id: "house-robber-show",
    title: "House Robber — Skip Adjacent",
    subtitle: "dp[i] = max(dp[i-1], dp[i-2] + nums[i]).",
    kind: "kadane",
    practiceIds: ["house-robber"],
    cells: [2, 7, 9, 3, 1],
    hookBoard: "House Robber",
    hookSay: "Suno. Ghar loot, adjacent mat chhoona. Max money.",
    hookEn: "Listen. Rob houses, never adjacent ones. Max money.",
    hookHi: "सुनो। घर लूट, आस-पास वाले मत छूना। मैक्स पैसे।",
    hookStats: { ask: "max loot" },
    contractBoard: "Max non-adjacent sum",
    contractSay: "Example [2,7,9,3,1] → 2+9+1=12 ya 7+3+? Best 12.",
    contractEn: "Example [2,7,9,3,1] → 2+9+1=12 or 7+… Best 12.",
    contractHi: "उदाहरण [2,7,9,3,1] → 2+9+1=12। बेस्ट 12।",
    contractExtra: { stats: { expect: 12 } },
    wrongBoard: "Take every other",
    wrongSay: "Even/odd indexes only? Suboptimal. DP choice per house.",
    wrongEn: "Only even/odd indexes? Suboptimal. DP choice per house.",
    wrongHi: "सिर्फ ईवन/ऑड इंडेक्स? सबऑप्टिमल। हर घर पर DP चॉइस।",
    wrongExtra: { stats: { avoid: "fixed parity" } },
    ideaBoard: "Skip or take",
    ideaSay: "House i pe: skip (prev best) YA take + prev2.",
    ideaEn: "At house i: skip (prev best) OR take + best from i-2.",
    ideaHi: "घर i पर: स्किप (prev बेस्ट) या लो + i-2 बेस्ट।",
    ideaExtra: { codeLine: "int prev2=0, prev1=0;" },
    trickBoard: "Rolling vars",
    trickSay: "cur = max(prev1, prev2 + nums[i]); shift. O(1) space.",
    trickEn: "cur = max(prev1, prev2 + nums[i]); shift. O(1) space.",
    trickHi: "cur = max(prev1, prev2 + nums[i]); शिफ्ट। O(1) स्पेस।",
    trickExtra: { codeLine: "int cur = max(prev1, prev2 + x);" },
    dry: [
      { board: "First houses", say: "2 → best 2. 7 → max(2,7)=7.", sayEn: "2 → best 2. 7 → max(2,7)=7.", sayHi: "2 → बेस्ट 2। 7 → max(2,7)=7।", hi: [0, 1], pointers: { i: 1 }, stats: { prev1: 7 } },
      { board: "Take 9", say: "9: max(7, 2+9)=11. Phir 3: max(11,7+3)=11.", sayEn: "9: max(7, 2+9)=11. Then 3: max(11,7+3)=11.", sayHi: "9: max(7, 2+9)=11। फिर 3: max(11,7+3)=11।", hi: [2, 3], pointers: { i: 3 }, stats: { best: 11 }, gesture: "write" },
      { board: "Take 1", say: "1: max(11, 11+1)=12. Answer 12.", sayEn: "1: max(11, 11+1)=12. Answer 12.", sayHi: "1: max(11, 11+1)=12। जवाब 12।", hi: [0, 2, 4], stats: { answer: 12 }, codeLine: "return prev1;", gesture: "celebrate" },
    ],
    wrapBoard: "Loot 12",
    wrapSay: "Adjacent skip DP. Ab likho.",
    wrapEn: "Adjacent-skip DP. Now write it.",
    wrapHi: "एडजेसेंट-स्किप DP। अब लिखो।",
    wrapExtra: { stats: { answer: 12, time: "O(n)" } },
  }),

  recipeShow({
    id: "coin-change-show",
    title: "Coin Change — Unbounded Knapsack DP",
    subtitle: "dp[x] = min coins to make amount x; try each coin.",
    kind: "kadane",
    practiceIds: ["coin-change"],
    cells: [1, 2, 5],
    hookBoard: "Coin Change",
    hookSay: "Suno. Coins unlimited. Amount banane ke minimum coins.",
    hookEn: "Listen. Unlimited coins. Minimum coins to make the amount.",
    hookHi: "सुनो। अनलिमिटेड कॉइन्स। अमाउंट बनाने के मिनिमम कॉइन्स।",
    hookStats: { amount: 11, coins: "1,2,5" },
    contractBoard: "Min count or -1",
    contractSay: "Impossible ho to -1. Yahan 11 = 5+5+1 → 3 coins.",
    contractEn: "If impossible return -1. Here 11 = 5+5+1 → 3 coins.",
    contractHi: "असंभव हो तो -1। यहाँ 11 = 5+5+1 → 3 कॉइन्स।",
    contractExtra: { stats: { expect: 3 } },
    wrongBoard: "Greedy always",
    wrongSay: "Hamesha bada coin? Kabhi fail. DP safe.",
    wrongEn: "Always take largest coin? Sometimes fails. DP is safe.",
    wrongHi: "हमेशा बड़ा कॉइन? कभी फेल। DP सेफ।",
    wrongExtra: { stats: { avoid: "blind greedy" } },
    ideaBoard: "dp[amount+1]",
    ideaSay: "dp[0]=0. Baaki INF. Har coin se amounts update.",
    ideaEn: "dp[0]=0. Rest INF. Update amounts using each coin.",
    ideaHi: "dp[0]=0। बाकी INF। हर कॉइन से अमाउंट्स अपडेट।",
    ideaExtra: { codeLine: "vector<int> dp(amount+1, INF); dp[0]=0;" },
    trickBoard: "Relax with coin",
    trickSay: "dp[x] = min(dp[x], dp[x-coin]+1) jab x>=coin.",
    trickEn: "dp[x] = min(dp[x], dp[x-coin]+1) when x>=coin.",
    trickHi: "dp[x] = min(dp[x], dp[x-coin]+1) जब x>=coin।",
    trickExtra: { codeLine: "dp[x] = min(dp[x], dp[x-c]+1);" },
    dry: [
      { board: "Fill small", say: "Coin 1 se sab dp[x]=x. Coin 2 improve karta.", sayEn: "Coin 1 sets dp[x]=x. Coin 2 improves some.", sayHi: "कॉइन 1 से dp[x]=x। कॉइन 2 सुधारता।", stats: { "dp[4]": 2 }, gesture: "write" },
      { board: "Coin 5", say: "dp[5]=1, dp[10]=2, dp[11]=min(11, dp[6]+1)… → 3.", sayEn: "dp[5]=1, dp[10]=2, dp[11] becomes 3.", sayHi: "dp[5]=1, dp[10]=2, dp[11] बनता 3।", stats: { "dp[11]": 3 }, gesture: "point" },
      { board: "Answer 3", say: "Min coins 3. INF bacha to -1.", sayEn: "Min coins 3. If INF remains, return -1.", sayHi: "मिन कॉइन्स 3। INF बचा तो -1।", stats: { answer: 3 }, codeLine: "return dp[amount] >= INF ? -1 : dp[amount];", gesture: "celebrate" },
    ],
    wrapBoard: "3 coins",
    wrapSay: "Unbounded DP classic. Ab likho.",
    wrapEn: "Unbounded DP classic. Now write it.",
    wrapHi: "अनबाउंडेड DP क्लासिक। अब लिखो।",
    wrapExtra: { stats: { answer: 3, time: "O(amount * coins)" } },
  }),

  recipeShow({
    id: "intersection-show",
    title: "Intersection of Two Arrays II — Freq Map",
    subtitle: "Count one array; consume counts while walking the other.",
    kind: "hash-map",
    practiceIds: ["intersection-two-arrays-ii"],
    cells: [1, 2, 2, 1],
    hookBoard: "Array Intersection II",
    hookSay: "Suno. Dono arrays ka multiset intersection — frequencies ka min.",
    hookEn: "Listen. Multiset intersection of two arrays — min of frequencies.",
    hookHi: "सुनो। दोनों ऐरे का मल्टीसेट इंटरसेक्शन — फ़्रीक्वेंसी का मिन।",
    hookStats: { nums2: "2 2", ask: "intersection" },
    contractBoard: "With multiplicity",
    contractSay: "2 do baar dono mein → result mein do baar. Order free.",
    contractEn: "2 appears twice in both → twice in result. Order free.",
    contractHi: "2 दोनों में दो बार → रिजल्ट में दो बार। ऑर्डर फ्री।",
    contractExtra: { stats: { expect: "[2, 2]" } },
    wrongBoard: "Set intersection",
    wrongSay: "Set unique only — multiplicity toot. Freq map chahiye.",
    wrongEn: "A set is unique-only — multiplicity breaks. Need a freq map.",
    wrongHi: "सेट सिर्फ यूनिक — मल्टीप्लिसिटी टूटे। फ़्रीक मैप चाहिए।",
    wrongExtra: { stats: { avoid: "unique set" } },
    ideaBoard: "Count nums1",
    ideaSay: "Chhote array pe freq. Dusre pe walk, count>0 ho to lo aur --.",
    ideaEn: "Freq on the smaller array. Walk the other; take when count>0 and --.",
    ideaHi: "छोटे ऐरे पर फ़्रीक। दूसरे पर वॉक; count>0 हो तो लो और --।",
    ideaExtra: { map: { "1": 2, "2": 2 }, codeLine: "unordered_map<int,int> freq;" },
    trickBoard: "Decrement on take",
    trickSay: "Jab push karo, freq[x]--. Zero ke baad mat lo.",
    trickEn: "When you push, freq[x]--. Do not take after zero.",
    trickHi: "जब पुश करो, freq[x]--। ज़ीरो के बाद मत लो।",
    trickExtra: { codeLine: "if (freq[x]-- > 0) ans.push_back(x);" },
    dry: [
      { board: "Map ready", say: "nums1 counts: 1→2, 2→2.", sayEn: "nums1 counts: 1→2, 2→2.", sayHi: "nums1 काउंट्स: 1→2, 2→2।", map: { "1": 2, "2": 2 }, stats: { built: "freq" }, gesture: "write" },
      { board: "Consume 2s", say: "nums2=[2,2]. Dono 2 lo. freq[2] 2→0. Result [2,2].", sayEn: "nums2=[2,2]. Take both 2s. freq[2] 2→0. Result [2,2].", sayHi: "nums2=[2,2]। दोनों 2 लो। freq[2] 2→0। रिजल्ट [2,2]।", cells: [2, 2], map: { "1": 2, "2": 0 }, stats: { answer: "[2, 2]" }, gesture: "celebrate" },
      { board: "Done", say: "Multiset intersection complete.", sayEn: "Multiset intersection complete.", sayHi: "मल्टीसेट इंटरसेक्शन पूरा।", cells: [2, 2], stats: { status: "done" }, gesture: "celebrate" },
    ],
    wrapBoard: "[2, 2]",
    wrapSay: "Freq consume pattern. Ab likho.",
    wrapEn: "Freq-consume pattern. Now write it.",
    wrapHi: "फ़्रीक-कंज्यूम पैटर्न। अब लिखो।",
    wrapExtra: { cells: [2, 2], stats: { time: "O(n+m)" } },
  }),

  recipeShow({
    id: "max-consec-ones-show",
    title: "Max Consecutive Ones — Streak Counter",
    subtitle: "cur++ on 1, reset on 0; track the max.",
    kind: "array-scan",
    practiceIds: ["max-consecutive-ones"],
    cells: [1, 1, 0, 1, 1, 1],
    hookBoard: "Max Consecutive Ones",
    hookSay: "Suno. Array mein 1s ki sabse lambi continuous streak.",
    hookEn: "Listen. Longest continuous streak of 1s in the array.",
    hookHi: "सुनो। ऐरे में 1s की सबसे लंबीContinuous स्ट्रीक।",
    hookStats: { ask: "max ones streak" },
    contractBoard: "Return length",
    contractSay: "Yahan pehle streak 2, baad mein 3. Answer 3.",
    contractEn: "Here first streak 2, later 3. Answer 3.",
    contractHi: "यहाँ पहली स्ट्रीक 2, बाद में 3। जवाब 3।",
    contractExtra: { stats: { expect: 3 } },
    wrongBoard: "Nested windows",
    wrongSay: "Har start se measure? Overkill. Single counter enough.",
    wrongEn: "Measure from every start? Overkill. A single counter is enough.",
    wrongHi: "हर स्टार्ट से मेज़र? ओवरकिल। सिंगल काउंटर काफी।",
    wrongExtra: { stats: { avoid: "nested" } },
    ideaBoard: "cur + best",
    ideaSay: "1 pe cur++. 0 pe cur=0. Har step best update.",
    ideaEn: "On 1, cur++. On 0, cur=0. Update best each step.",
    ideaHi: "1 पर cur++। 0 पर cur=0। हर स्टेप बेस्ट अपडेट।",
    ideaExtra: { codeLine: "int cur=0, best=0;" },
    trickBoard: "Reset carefully",
    trickSay: "Zero aate hi reset — beech ka gap streak tod-ta.",
    trickEn: "Reset as soon as zero hits — a gap breaks the streak.",
    trickHi: "ज़ीरो आते ही रीसेट — बीच का गैप स्ट्रीक तोड़ता।",
    trickExtra: { codeLine: "if (x==1) best=max(best, ++cur); else cur=0;" },
    dry: [
      { board: "Streak 2", say: "1,1 → cur=2, best=2. Phir 0 reset.", sayEn: "1,1 → cur=2, best=2. Then 0 resets.", sayHi: "1,1 → cur=2, best=2। फिर 0 रीसेट।", hi: [0, 1], pointers: { i: 1 }, stats: { cur: 2, best: 2 } },
      { board: "Streak 3", say: "1,1,1 → cur=3, best=3.", sayEn: "1,1,1 → cur=3, best=3.", sayHi: "1,1,1 → cur=3, best=3।", hi: [3, 4, 5], window: [3, 5], pointers: { i: 5 }, stats: { cur: 3, best: 3 }, gesture: "celebrate" },
      { board: "Answer 3", say: "Max consecutive ones = 3.", sayEn: "Max consecutive ones = 3.", sayHi: "मैक्सConsecutive ओन्स = 3।", stats: { answer: 3 }, codeLine: "return best;", gesture: "celebrate" },
    ],
    wrapBoard: "Answer 3",
    wrapSay: "Simple scan. Ab likho.",
    wrapEn: "Simple scan. Now write it.",
    wrapHi: "सिंपल स्कैन। अब लिखो।",
    wrapExtra: { stats: { answer: 3, time: "O(n)" } },
  }),

  recipeShow({
    id: "search-insert-show",
    title: "Search Insert Position — Lower Bound",
    subtitle: "Binary search the first index where nums[i] ≥ target.",
    kind: "two-pointers",
    practiceIds: ["search-insert"],
    cells: [1, 3, 5, 6],
    hookBoard: "Search Insert",
    hookSay: "Suno. Sorted array. Target ka index, ya insert kahan hoga.",
    hookEn: "Listen. Sorted array. Index of target, or where it would insert.",
    hookHi: "सुनो। सॉर्टेड ऐरे। टारगेट का इंडेक्स, या इन्सर्ट कहाँ होगा।",
    hookStats: { target: 5, ask: "index / insert pos" },
    contractBoard: "Lower bound",
    contractSay: "Pehla index jahan nums[i] >= target. 5→2, 2→1, 7→4.",
    contractEn: "First index where nums[i] >= target. 5→2, 2→1, 7→4.",
    contractHi: "पहला इंडेक्स जहाँ nums[i] >= target। 5→2, 2→1, 7→4।",
    contractExtra: { stats: { "t=5": 2 } },
    wrongBoard: "Linear scan",
    wrongSay: "Left se walk O(n). Binary O(log n) chahiye.",
    wrongEn: "Walk from the left is O(n). Want binary O(log n).",
    wrongHi: "लेफ्ट से वॉक O(n)। बाइनरी O(log n) चाहिए।",
    wrongExtra: { stats: { avoid: "linear" } },
    ideaBoard: "Classic BS",
    ideaSay: "L,R. mid. Agar nums[mid] < target, L=mid+1. Else R=mid-1.",
    ideaEn: "L,R. mid. If nums[mid] < target, L=mid+1. Else R=mid-1.",
    ideaHi: "L,R। mid। अगर nums[mid] < target, L=mid+1। वरना R=mid-1।",
    ideaExtra: { pointers: { L: 0, R: 3 }, codeLine: "int L=0, R=n-1;" },
    trickBoard: "Return L",
    trickSay: "Loop ke baad L hi insert/find position. Lower bound.",
    trickEn: "After the loop, L is the insert/find position. Lower bound.",
    trickHi: "लूप के बाद L ही इन्सर्ट/फाइंड पोज़ीशन। लोअर बाउंड।",
    trickExtra: { codeLine: "return L;" },
    dry: [
      { board: "Find 5", say: "mid points toward 5. Found at index 2.", sayEn: "mid moves toward 5. Found at index 2.", sayHi: "mid 5 की तरफ़। इंडेक्स 2 पर मिला।", hi: [2], pointers: { L: 2, R: 2, mid: 2 }, stats: { found: 2 } },
      { board: "Insert 2", say: "target 2: L settles at 1. Insert before 3.", sayEn: "target 2: L settles at 1. Insert before 3.", sayHi: "टारगेट 2: L 1 पर। 3 से पहले इन्सर्ट।", hi: [1], pointers: { L: 1 }, stats: { insert: 1 }, gesture: "write" },
      { board: "Insert 7", say: "target 7: L=4 end pe. Pattern solid.", sayEn: "target 7: L=4 at the end. Pattern solid.", sayHi: "टारगेट 7: L=4 अंत पर। पैटर्न सॉलिड।", pointers: { L: 4 }, stats: { insert: 4 }, gesture: "celebrate" },
    ],
    wrapBoard: "Lower bound",
    wrapSay: "Binary search template. Ab likho.",
    wrapEn: "Binary search template. Now write it.",
    wrapHi: "बाइनरी सर्च टेम्पलेट। अब लिखो।",
    wrapExtra: { stats: { time: "O(log n)" } },
  }),

  recipeShow({
    id: "first-last-show",
    title: "First & Last Position — Twin Bounds",
    subtitle: "Lower bound for first; upper bound − 1 for last.",
    kind: "two-pointers",
    practiceIds: ["first-last-position"],
    cells: [5, 7, 7, 8, 8, 10],
    hookBoard: "First and Last Position",
    hookSay: "Suno. Sorted array mein target ka pehla aur aakhri index.",
    hookEn: "Listen. First and last index of target in a sorted array.",
    hookHi: "सुनो। सॉर्टेड ऐरे में टारगेट का पहला और आखिरी इंडेक्स।",
    hookStats: { target: 8, ask: "[first, last]" },
    contractBoard: "[-1,-1] if missing",
    contractSay: "8 → [3,4]. 6 missing → [-1,-1].",
    contractEn: "8 → [3,4]. 6 missing → [-1,-1].",
    contractHi: "8 → [3,4]। 6 मिसिंग → [-1,-1]।",
    contractExtra: { stats: { expect: "[3, 4]" }, hi: [3, 4] },
    wrongBoard: "One BS then expand",
    wrongSay: "Find karke left/right expand — worst O(n). Do BS better.",
    wrongEn: "Find then expand left/right — worst O(n). Two BS is better.",
    wrongHi: "फाइंड करके लेफ्ट/राइट एक्सपैंड — वर्स्ट O(n)। दो BS बेहतर।",
    wrongExtra: { stats: { avoid: "linear expand" } },
    ideaBoard: "Two binary searches",
    ideaSay: "Lower bound = first. Upper bound - 1 = last.",
    ideaEn: "Lower bound = first. Upper bound - 1 = last.",
    ideaHi: "लोअर बाउंड = पहला। अपर बाउंड - 1 = आखिरी।",
    ideaExtra: { codeLine: "int lo = lower_bound(...); int hi = upper_bound(...)-1;" },
    trickBoard: "Validate",
    trickSay: "Agar lo out of range ya nums[lo]!=target → [-1,-1].",
    trickEn: "If lo out of range or nums[lo]!=target → [-1,-1].",
    trickHi: "अगर lo रेंज से बाहर या nums[lo]!=target → [-1,-1]।",
    trickExtra: { codeLine: "if (lo==n || nums[lo]!=target) return {-1,-1};" },
    dry: [
      { board: "Lower of 8", say: "Lower bound of 8 → index 3.", sayEn: "Lower bound of 8 → index 3.", sayHi: "8 का लोअर बाउंड → इंडेक्स 3।", hi: [3], pointers: { L: 3, R: 5 }, stats: { first: 3 }, gesture: "write" },
      { board: "Upper-1", say: "Upper bound 5, minus 1 → 4. Last index 4.", sayEn: "Upper bound 5, minus 1 → 4. Last index 4.", sayHi: "अपर बाउंड 5, माइनस 1 → 4। लास्ट 4।", hi: [3, 4], stats: { last: 4 }, gesture: "point" },
      { board: "Answer", say: "[3,4]. Twin binary searches done.", sayEn: "[3,4]. Twin binary searches done.", sayHi: "[3,4]। ट्विन बाइनरी सर्च डन।", hi: [3, 4], stats: { answer: "[3, 4]" }, codeLine: "return {3, 4};", gesture: "celebrate" },
    ],
    wrapBoard: "[3, 4]",
    wrapSay: "Lower + upper. Ab likho.",
    wrapEn: "Lower + upper. Now write it.",
    wrapHi: "लोअर + अपर। अब लिखो।",
    wrapExtra: { stats: { answer: "[3,4]", time: "O(log n)" } },
  }),

  recipeShow({
    id: "min-stack-show",
    title: "Min Stack — Twin Stacks",
    subtitle: "Value stack + mins stack; push and pop together.",
    kind: "array-scan",
    practiceIds: ["min-stack"],
    cells: [-2, 0, -3],
    hookBoard: "Min Stack",
    hookSay: "Suno. Stack design: push, pop, top, getMin — sab O(1).",
    hookEn: "Listen. Design a stack: push, pop, top, getMin — all O(1).",
    hookHi: "सुनो। स्टैक डिज़ाइन: push, pop, top, getMin — सब O(1)।",
    hookStats: { ask: "O(1) getMin" },
    contractBoard: "All ops O(1)",
    contractSay: "Har op constant time. Example: push -2,0,-3 → getMin -3.",
    contractEn: "Every op constant time. Example: push -2,0,-3 → getMin -3.",
    contractHi: "हर ऑप कॉन्स्टेंट टाइम। उदाहरण: push -2,0,-3 → getMin -3।",
    contractExtra: { stats: { demo: "getMin → -3" } },
    wrongBoard: "Scan for min",
    wrongSay: "Har getMin pe scan? O(n). Parallel min stack chahiye.",
    wrongEn: "Scan on every getMin? O(n). Need a parallel min stack.",
    wrongHi: "हर getMin पर स्कैन? O(n)। पैरेलल मिन स्टैक चाहिए।",
    wrongExtra: { stats: { avoid: "scan" } },
    ideaBoard: "vals + mins",
    ideaSay: "Do stacks. Push pe mins.push(min(val, mins.top())).",
    ideaEn: "Two stacks. On push, mins.push(min(val, mins.top())).",
    ideaHi: "दो स्टैक्स। पुश पर mins.push(min(val, mins.top()))।",
    ideaExtra: { codeLine: "stack<int> vals, mins;" },
    trickBoard: "Pop both",
    trickSay: "Pop dono se. getMin = mins.top(). Sync mat todo.",
    trickEn: "Pop from both. getMin = mins.top(). Keep them in sync.",
    trickHi: "पॉप दोनों से। getMin = mins.top()। सिंक मत तोड़ो।",
    trickExtra: { codeLine: "void pop(){ vals.pop(); mins.pop(); }" },
    dry: [
      { board: "Push -2,0", say: "vals[-2,0], mins[-2,-2]. Min abhi -2.", sayEn: "vals[-2,0], mins[-2,-2]. Min is still -2.", sayHi: "vals[-2,0], mins[-2,-2]। मिन अभी -2।", cells: [-2, 0], stats: { min: -2 }, map: { vals: "-2,0", mins: "-2,-2" }, gesture: "write" },
      { board: "Push -3", say: "vals[-2,0,-3], mins[-2,-2,-3]. getMin=-3.", sayEn: "vals[-2,0,-3], mins[-2,-2,-3]. getMin=-3.", sayHi: "vals[-2,0,-3], mins[-2,-2,-3]। getMin=-3।", cells: [-2, 0, -3], stats: { getMin: -3 }, gesture: "point" },
      { board: "Pop", say: "Pop → top=0, getMin=-2. Design works.", sayEn: "Pop → top=0, getMin=-2. Design works.", sayHi: "पॉप → top=0, getMin=-2। डिज़ाइन वर्क्स।", cells: [-2, 0], stats: { top: 0, getMin: -2 }, codeLine: "getMin(); // -2", gesture: "celebrate" },
    ],
    wrapBoard: "O(1) min",
    wrapSay: "Twin stacks. Ab implement karo.",
    wrapEn: "Twin stacks. Now implement it.",
    wrapHi: "ट्विन स्टैक्स। अब इम्प्लीमेंट करो।",
    wrapExtra: { stats: { time: "O(1) ops" } },
  }),

  recipeShow({
    id: "max-consec-iii-show",
    title: "Max Consecutive Ones III — Flip ≤ k Zeros",
    subtitle: "Longest window that contains at most k zeros.",
    kind: "sliding-window",
    practiceIds: ["max-consec-ones-iii"],
    cells: [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0],
    hookBoard: "Max Ones III",
    hookSay: "Suno. At most k zeros flip karke longest 1s window.",
    hookEn: "Listen. Longest 1s window after flipping at most k zeros.",
    hookHi: "सुनो। ज़्यादा से ज़्यादा k ज़ीरो फ्लिप करके सबसे लंबी 1s विंडो।",
    hookStats: { k: 2, ask: "max window len" },
    contractBoard: "At most k zeros",
    contractSay: "Window mein zeros ≤ k. Yahan k=2 → best length 6.",
    contractEn: "Window may hold ≤ k zeros. Here k=2 → best length 6.",
    contractHi: "विंडो में ज़ीरो ≤ k। यहाँ k=2 → बेस्ट लेंथ 6।",
    contractExtra: { stats: { expect: 6 } },
    wrongBoard: "Try every flip set",
    wrongSay: "Kaunse zeros flip? Exponential. Sliding window smart.",
    wrongEn: "Which zeros to flip? Exponential. Sliding window is smart.",
    wrongHi: "कौन से ज़ीरो फ्लिप? एक्सपोनेंशियल। स्लाइडिंग विंडो स्मार्ट।",
    wrongExtra: { stats: { avoid: "subset flips" } },
    ideaBoard: "Zero count window",
    ideaSay: "R expand. Zero aaye to count++. Jab count>k, L aage.",
    ideaEn: "Expand R. Zeros increment count. While count>k, advance L.",
    ideaHi: "R एक्सपैंड। ज़ीरो पर count++। जब count>k, L आगे।",
    ideaExtra: { pointers: { L: 0, R: 0 }, codeLine: "int L=0, zeros=0, best=0;" },
    trickBoard: "Max length",
    trickSay: "Har valid window pe best = max(best, R-L+1).",
    trickEn: "On every valid window, best = max(best, R-L+1).",
    trickHi: "हर वैलिड विंडो पर best = max(best, R-L+1)।",
    trickExtra: { codeLine: "best = max(best, R-L+1);" },
    dry: [
      { board: "Grow", say: "R badhao. Teen zeros se pehle window healthy with k=2.", sayEn: "Grow R. Before the third zero the window is healthy with k=2.", sayHi: "R बढ़ाओ। तीसरे ज़ीरो से पहले विंडो k=2 से हेल्दी।", hi: [0, 1, 2, 3, 4], window: [0, 4], pointers: { L: 0, R: 4 }, stats: { zeros: 2, len: 5 } },
      { board: "Shrink", say: "Teesra zero → zeros>k. L aage zero cross. Window salvage.", sayEn: "Third zero → zeros>k. Advance L past a zero. Salvage window.", sayHi: "तीसरा ज़ीरो → zeros>k। L आगे ज़ीरो पार। विंडो बचाओ।", hi: [3, 4, 5, 6, 7, 8, 9], window: [3, 9], pointers: { L: 3, R: 9 }, stats: { zeros: 2, len: 6 }, gesture: "write" },
      { board: "Best 6", say: "Best length 6. Flip-two zeros window jeeti.", sayEn: "Best length 6. The flip-two-zeros window wins.", sayHi: "बेस्ट लेंथ 6। दो-ज़ीरो-फ्लिप विंडो जीती।", window: [5, 10], stats: { answer: 6 }, codeLine: "return best;", gesture: "celebrate" },
    ],
    wrapBoard: "Answer 6",
    wrapSay: "At-most-k zeros window. Ab likho.",
    wrapEn: "At-most-k zeros window. Now write it.",
    wrapHi: "एट-मोस्ट-k ज़ीरो विंडो। अब लिखो।",
    wrapExtra: { stats: { answer: 6, time: "O(n)" } },
  }),
];
